# Generated by Django 6.0.7 on 2026-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_stocktake_two_person_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='sales_prices_include_tax',
            field=models.BooleanField(default=False, help_text='Whether prices entered on new sales orders include tax.'),
        ),
    ]
