# Generated by Django 6.0.7 on 2026-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_workspace_sales_prices_include_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="garden_setup_state",
            field=models.CharField(
                choices=[
                    ("pending", "Not started"),
                    ("skipped", "Skipped"),
                    ("complete", "Complete"),
                ],
                default="pending",
                help_text="Whether the guided garden setup has been finished or declined. An established workspace is never offered it, because it already has a garden.",
                max_length=16,
            ),
        ),
    ]
