# Generated by Django 6.0.7 on 2026-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_workspace_garden_setup_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="garden_experience",
            field=models.CharField(
                choices=[("basic", "Basic"), ("advanced", "Advanced")],
                default="basic",
                help_text="Whether Garden-profile screens show simplified defaults or full stock, costing, and traceability detail. Ignored in Nursery profile, which always behaves as Advanced.",
                max_length=16,
            ),
        ),
    ]
