# Generated by Django 6.1 on 2026-08-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_workspace_garden_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="business_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The seller address printed on taxable supply and correction documents.",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="legal_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The registered legal name of the entity making supplies, if it differs from the name this workspace is known by. A taxable supply document is issued under it.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="trading_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name the business trades under, where that differs from its legal name. Shown on a document alongside the legal name rather than instead of it.",
                max_length=255,
            ),
        ),
    ]
