# Generated by Django 6.1 on 2026-08-27 09:29

import django.core.validators
import django.db.models.deletion
import uuid
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchasing", "0002_businessexpense_paid_on"),
        ("workspaces", "0007_workspace_seller_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeTaxYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_end", models.DateField()),
                (
                    "basis",
                    models.CharField(
                        choices=[("cash", "Cash"), ("accrual", "Accrual")], max_length=8
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized")],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "frozen_report",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("retain_until", models.DateField(editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="bookkeeping.incometaxyear",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_end", "-revision"],
            },
        ),
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("counterparty", models.CharField(max_length=255)),
                ("opened_on", models.DateField()),
                ("closed_on", models.DateField(blank=True, null=True)),
                ("currency_code", models.CharField(max_length=3)),
                ("notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BookkeepingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("other_income", "Other income"),
                            ("owner_contribution", "Owner contribution"),
                            ("owner_drawing", "Owner drawing"),
                            ("liability_advance", "Liability advance"),
                            ("liability_repayment", "Liability repayment"),
                            ("cash_adjustment", "Cash adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_on", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "counterparty",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "amount_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "tax_treatment",
                    models.CharField(default="out_of_scope", max_length=32),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "account_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("operation_key", models.UUIDField(default=uuid.uuid4)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="bookkeeping.bookkeepingentry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "liability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="bookkeeping.liability",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StockValuationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("saleable_plants", "Saleable plants"),
                            ("work_in_progress", "Work in progress"),
                            ("seed_media", "Seed and media"),
                            ("packaging", "Packaging"),
                            ("other", "Other trading stock"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(blank=True, default="manual", max_length=64),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=24, null=True
                    ),
                ),
                ("unit_code", models.CharField(blank=True, default="", max_length=16)),
                (
                    "original_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cost", "Cost"),
                            ("discounted_selling", "Discounted selling price"),
                            ("replacement", "Replacement price"),
                            ("market_selling", "Market selling value"),
                            ("opening_value", "Opening-value concession"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("assumptions", models.TextField(blank=True, default="")),
                ("derived", models.BooleanField(default=False, editable=False)),
                ("provisional", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "income_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_lines",
                        to="bookkeeping.incometaxyear",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "source_type", "source_id", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TaxAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=128)),
                ("acquired_on", models.DateField()),
                ("first_used_on", models.DateField(blank=True, null=True)),
                ("cost_incl_tax", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "recoverable_tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("tax_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_code", models.CharField(max_length=3)),
                ("disposed_on", models.DateField(blank=True, null=True)),
                (
                    "disposal_proceeds",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_assets",
                        to="purchasing.businessexpense",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "pk"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income_year_end", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("dv", "Diminishing value"),
                            ("sl", "Straight line"),
                            ("none", "No depreciation claimed"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "business_use_percent",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "months_used",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "opening_tax_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "depreciation_claimed",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "disposal_adjustment",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "closing_tax_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="bookkeeping.taxasset",
                    ),
                ),
            ],
            options={
                "ordering": ["income_year_end", "asset_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="incometaxyear",
            constraint=models.UniqueConstraint(
                fields=("workspace", "year_end", "revision"),
                name="bookkeeping_income_year_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="liability",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"), name="bookkeeping_liability_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookkeepingentry",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="bookkeeping_entry_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockvaluationline",
            constraint=models.UniqueConstraint(
                fields=("income_year", "source_type", "source_id"),
                name="bookkeeping_stock_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxasset",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"), name="bookkeeping_tax_asset_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationschedule",
            constraint=models.UniqueConstraint(
                fields=("asset", "income_year_end"),
                name="bookkeeping_asset_year_unique",
            ),
        ),
    ]
