# Generated by Django 6.0.7 on 2026-08-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("garden", "0006_gardengeometryconfirmation"),
        ("inventory", "0006_stockreceipt_price_includes_tax"),
        ("plantings", "0024_harvest"),
        ("seedtrays", "0005_seedtraygeneration_seedtraygenerationevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputapplicationtarget",
            name="seed_tray_generation",
            field=models.ForeignKey(
                blank=True,
                help_text="The tray fill this cell belonged to when the input was applied.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_targets",
                to="seedtrays.seedtraygeneration",
            ),
        ),
        migrations.AddConstraint(
            model_name="inputapplicationtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("seed_tray_generation__isnull", True),
                    ("target_type", "seed_tray_cell"),
                    _connector="OR",
                ),
                name="application_target_generation_needs_cell",
            ),
        ),
    ]
