# Generated by Django 6.0.7 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_point_applications_at_the_locations_app'),
        ('plantings', '0029_growthstage_nurseryobservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputapplicationtarget',
            name='target_type',
            field=models.CharField(choices=[('batch', 'Production batch'), ('seed_tray_cell', 'Tray cell'), ('specific_plant', 'Plant'), ('plant_cohort', 'Plant cohort'), ('inventory_unit', 'Serialized unit'), ('garden_area', 'Garden area'), ('garden_bed', 'Garden bed'), ('garden_row', 'Garden row'), ('garden_square', 'Garden square')], max_length=24),
        ),
        migrations.AddField(
            model_name='inputapplicationtarget',
            name='plant_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_targets', to='plantings.plantcohort'),
        ),
        migrations.RemoveConstraint(
            model_name='inputapplicationtarget',
            name='application_target_identity',
        ),
        migrations.AddConstraint(
            model_name='inputapplicationtarget',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('batch__isnull', False), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'batch')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', False), ('specific_plant__isnull', True), ('target_type', 'seed_tray_cell')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', False), ('target_type', 'specific_plant')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', False), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'plant_cohort')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', False), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'inventory_unit')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', False), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'garden_area')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', False), ('garden_row__isnull', True), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'garden_bed')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', False), ('garden_square__isnull', True), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'garden_row')),
                    models.Q(('batch__isnull', True), ('garden_area__isnull', True), ('garden_bed__isnull', True), ('garden_row__isnull', True), ('garden_square__isnull', False), ('inventory_unit__isnull', True), ('plant_cohort__isnull', True), ('seed_tray_cell__isnull', True), ('specific_plant__isnull', True), ('target_type', 'garden_square')),
                    _connector='OR',
                ),
                name='application_target_identity',
            ),
        ),
        migrations.AddConstraint(
            model_name='inputapplicationtarget',
            constraint=models.UniqueConstraint(condition=models.Q(('plant_cohort__isnull', False)), fields=('line', 'plant_cohort'), name='application_target_unique_plant_cohort'),
        ),
    ]
