# Generated by Django 6.1 on 2026-08-22 23:15

import django.core.validators
import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0004_classify_sales_lines_for_gst"),
        ("tax", "0004_widen_the_entered_gst_number"),
        ("workspaces", "0007_workspace_seller_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("seller_legal_name", models.CharField(max_length=255)),
                (
                    "seller_trading_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("seller_address", models.TextField(blank=True, default="")),
                (
                    "seller_gst_number",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("buyer_address", models.TextField(blank=True, default="")),
                (
                    "buyer_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Any other identifier for the recipient a supply over $1,000 may be identified by instead of an address — an NZBN, a phone number, an email address, or a website.",
                        max_length=255,
                    ),
                ),
                ("document_number", models.CharField(max_length=32)),
                (
                    "issued_on",
                    models.DateField(
                        help_text="The document date, as a workspace-local business date. This is the time of supply the invoice basis recognises on, so it is a date rather than an instant."
                    ),
                ),
                (
                    "taxable_supply",
                    models.BooleanField(
                        help_text="Whether the seller was GST registered on the document date, and the document is therefore taxable supply information."
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        help_text="The value band whose required information this document met.",
                        max_length=16,
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("tax_total", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "previously_invoiced",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The value of every live document issued against this order before this one.",
                        max_digits=18,
                    ),
                ),
                (
                    "paid_to_date",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Payments received net of refunds, on or before the document date. A deposit taken in advance shows up here rather than as a line.",
                        max_digits=18,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What was still owed when this document was issued, floored at zero. An excess is reported separately rather than as a negative balance, because money beyond the value of a supply is not a discount on it.",
                        max_digits=18,
                    ),
                ),
                (
                    "overpaid_at_issue",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Payments beyond everything invoiced, as at the document date.",
                        max_digits=18,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_documents",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "seller_registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GST arrangement in force on the document date, or empty when the seller was not registered and the document is therefore not taxable supply information.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tax.gstregistration",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["issued_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplyCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("seller_legal_name", models.CharField(max_length=255)),
                (
                    "seller_trading_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("seller_address", models.TextField(blank=True, default="")),
                (
                    "seller_gst_number",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("buyer_address", models.TextField(blank=True, default="")),
                (
                    "buyer_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Any other identifier for the recipient a supply over $1,000 may be identified by instead of an address — an NZBN, a phone number, an email address, or a website.",
                        max_length=255,
                    ),
                ),
                ("document_number", models.CharField(max_length=32)),
                (
                    "correction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=16,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("return", "Goods returned"),
                            ("discount", "Discount or price adjustment"),
                            ("wrong_rate", "Wrong GST rate or treatment"),
                            ("cancellation", "Supply cancelled"),
                            ("partial_credit", "Part of the supply credited"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "corrected_on",
                    models.DateField(
                        help_text="The workspace-local business date the correction was made."
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.customer",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_corrections",
                        to="sales.refund",
                    ),
                ),
                (
                    "sales_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_corrections",
                        to="sales.salesreturn",
                    ),
                ),
                (
                    "seller_registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GST arrangement in force on the document date, or empty when the seller was not registered and the document is therefore not taxable supply information.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tax.gstregistration",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="billing.supplydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["corrected_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplyDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "tax_treatment",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("gross_ex_tax", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "discount_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("tax_total", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="billing.supplydocument",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_document_lines",
                        to="sales.salesorderline",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplyDocumentCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commercial_position", models.PositiveIntegerField()),
                (
                    "fulfillment_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_document_coverage",
                        to="sales.fulfillmentline",
                    ),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage",
                        to="billing.supplydocumentline",
                    ),
                ),
            ],
            options={
                "ordering": ["commercial_position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplyCorrectionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "tax_treatment",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("tax_total", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "correction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="billing.supplycorrection",
                    ),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_lines",
                        to="billing.supplydocumentline",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DocumentNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(max_length=16)),
                ("next_number", models.PositiveBigIntegerField(default=1)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "series"),
                        name="billing_number_sequence_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supplydocument",
            index=models.Index(
                fields=["workspace", "issued_on"], name="billing_document_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocument",
            constraint=models.UniqueConstraint(
                fields=("workspace", "document_number"),
                name="billing_document_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocument",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="billing_document_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("tier__in", ("low", "standard", "full"))),
                name="billing_document_tier_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("balance_due__gte", 0),
                    ("overpaid_at_issue__gte", 0),
                    ("total_incl_tax__gte", 0),
                ),
                name="billing_document_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("taxable_supply", True),
                    models.Q(("seller_gst_number", ""), ("tax_total", 0)),
                    _connector="OR",
                ),
                name="billing_document_untaxed_when_unregistered",
            ),
        ),
        migrations.AddIndex(
            model_name="supplycorrection",
            index=models.Index(
                fields=["workspace", "corrected_on"], name="billing_correction_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycorrection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "document_number"),
                name="billing_correction_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycorrection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="billing_correction_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal_ex_tax__gte", 0),
                    ("tax_total__gte", 0),
                    ("total_incl_tax__gte", 0),
                ),
                name="billing_correction_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocumentline",
            constraint=models.UniqueConstraint(
                fields=("document", "order_line"),
                name="billing_document_line_order_line_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="billing_document_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocumentcoverage",
            constraint=models.UniqueConstraint(
                fields=("document_line", "commercial_position"),
                name="billing_coverage_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplydocumentcoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(("commercial_position__gte", 1)),
                name="billing_coverage_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycorrectionline",
            constraint=models.UniqueConstraint(
                fields=("correction", "document_line"),
                name="billing_correction_line_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycorrectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_incl_tax__gte", 0)),
                name="billing_correction_line_not_negative",
            ),
        ),
    ]
