# Generated by Django 5.0.6 on 2024-07-07 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garden", "0002_gardenrow_gardensquare"),
        ("seeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GardenRowDirectSowPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planted", models.DateField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garden.gardenrow",
                    ),
                ),
                (
                    "seeds_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seeds.seedpacket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GardenSquareDirectSowPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planted", models.DateField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garden.gardensquare",
                    ),
                ),
                (
                    "seeds_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seeds.seedpacket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeedTrayPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planted", models.DateField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=1024)),
                (
                    "seeds_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seeds.seedpacket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
