# Generated by Django 5.0.6 on 2024-07-12 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gardenrowdirectsowplanting",
            name="planted",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="gardensquaredirectsowplanting",
            name="planted",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="seedtrayplanting",
            name="planted",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
