# Generated by Django 5.0.8 on 2024-08-11 08:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0002_gardenrow_gardensquare"),
        ("plantings", "0002_alter_gardenrowdirectsowplanting_planted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GardenSquareTransplant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transplanted", models.DateField(default=datetime.date.today)),
                ("quantity", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garden.gardensquare",
                    ),
                ),
                (
                    "original_planting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plantings.seedtrayplanting",
                    ),
                ),
            ],
        ),
    ]
