# Generated by Django 6.0.1 on 2026-01-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0004_gardenrowdirectsowplanting_removed_and_more"),
        ("seedtrays", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedtrayplanting",
            name="seed_tray",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="seedtrays.seedtray",
            ),
        ),
        migrations.AlterField(
            model_name="seedtrayplanting",
            name="location",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
