# Generated by Django 6.0.1 on 2026-02-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0005_seedtrayplanting_seed_tray_and_more"),
        ("seedtrays", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedTrayCellPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seedtrays.seedtraycell",
                    ),
                ),
                (
                    "seed_tray_planting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_plantings",
                        to="plantings.seedtrayplanting",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seed_tray_planting", "cell"),
                        name="unique_cell_per_planting",
                    )
                ],
            },
        ),
    ]
