# Generated by Django 6.0.3 on 2026-03-07 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0009_specificplantlocation_unique_active_location_per_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gardenrowdirectsowplanting",
            name="planted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gardensquaredirectsowplanting",
            name="planted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gardensquaretransplant",
            name="transplanted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="seedtrayplanting",
            name="planted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="specificplant",
            name="germinated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="specificplantlocation",
            name="ended",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="specificplantlocation",
            name="started",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
