# Generated by Django 6.0.6 on 2026-07-18 06:22

from django.db import migrations, models


QUANTITY_MODELS = (
    'GardenRowDirectSowPlanting',
    'GardenSquareDirectSowPlanting',
    'GardenSquareTransplant',
    'SeedTrayCellPlanting',
    'SeedTrayPlanting',
)


def describe_rows(queryset):
    """Return a bounded description of rows that failed the audit."""
    count = queryset.count()
    row_ids = list(queryset.order_by('pk').values_list('pk', flat=True)[:20])
    suffix = '' if count <= len(row_ids) else f' (first 20 of {count})'
    return f'{row_ids}{suffix}'


def audit_positive_quantities(apps, _schema_editor):
    """Stop deployment rather than constraining corrupt quantity history."""
    problems = []
    for model_name in QUANTITY_MODELS:
        model = apps.get_model('plantings', model_name)
        invalid_rows = model.objects.filter(quantity__lt=1)
        if invalid_rows.count():
            problems.append(f'{model_name} IDs: {describe_rows(invalid_rows)}')

    if problems:
        raise RuntimeError(
            'Planting quantity audit failed. Repair non-positive quantities '
            f'before retrying the migration: {"; ".join(problems)}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0003_validate_garden_geometry"),
        ("plantings", "0013_validate_positive_quantities"),
        ("seeds", "0003_alter_seeds_supplier_delete_supplier"),
        ("seedtrays", "0002_datetimefield_created"),
    ]

    operations = [
        migrations.RunPython(audit_positive_quantities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="gardenrowdirectsowplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="row_sow_quantity_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="gardensquaredirectsowplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="square_sow_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardensquaretransplant",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="square_transplant_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraycellplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="seed_tray_cell_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtrayplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="seed_tray_quantity_gte_1",
            ),
        ),
    ]
