# Generated by Django 6.0.7 on 2026-08-02 00:18

import django.db.models.deletion
import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_remove_stocklot_inventory_lot_positive_initial_quantity_and_more",
        ),
        ("plantings", "0017_workspace_ownership"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SowingStockPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sowing_posting",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "replacement_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement",
                        to="plantings.sowingstockposting",
                    ),
                ),
                (
                    "row_planting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_postings",
                        to="plantings.gardenrowdirectsowplanting",
                    ),
                ),
                (
                    "square_planting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_postings",
                        to="plantings.gardensquaredirectsowplanting",
                    ),
                ),
                (
                    "tray_planting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_postings",
                        to="plantings.seedtrayplanting",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("row_planting__isnull", False),
                                ("square_planting__isnull", True),
                                ("tray_planting__isnull", True),
                            ),
                            models.Q(
                                ("row_planting__isnull", True),
                                ("square_planting__isnull", False),
                                ("tray_planting__isnull", True),
                            ),
                            models.Q(
                                ("row_planting__isnull", True),
                                ("square_planting__isnull", True),
                                ("tray_planting__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="sowing_posting_exactly_one_planting",
                    )
                ],
            },
        ),
    ]
