# Generated by Django 6.0.7 on 2026-08-03 10:39

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0021_require_planting_batch"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("germinated", "Germinated"),
                            ("ready", "Ready for sale or use"),
                            ("transplanted", "Transplanted or planted out"),
                            ("retained", "Retained"),
                            ("failed", "Failed"),
                            ("culled", "Culled"),
                            ("donated", "Donated"),
                            ("harvest_finished", "Harvest finished"),
                            ("corrected", "Corrected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plant_lifecycle_events",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="plantings.specificplant",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="plantings.plantlifecycleevent",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["plant", "occurred_at"],
                        name="plant_lifecycle_replay_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("event_type", "germinated")),
                        fields=("plant",),
                        name="plant_lifecycle_single_germination",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("event_type", "corrected"),
                                ("reversal_of__isnull", False),
                            ),
                            models.Q(
                                models.Q(("event_type", "corrected"), _negated=True),
                                ("reversal_of__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="plant_lifecycle_reversal_type",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reference", ""), _negated=True),
                        fields=("plant", "event_type", "reference"),
                        name="plant_lifecycle_reference_idempotent",
                    ),
                ],
            },
        ),
    ]
