# Generated by Django 6.0.7 on 2026-08-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0024_harvest"),
        ("seeds", "0006_map_legacy_packets_to_inventory"),
        ("seedtrays", "0005_seedtraygeneration_seedtraygenerationevent_and_more"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedtrayplanting",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sowings",
                to="seedtrays.seedtraygeneration",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtrayplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("generation__isnull", True),
                    ("seed_tray__isnull", False),
                    _connector="OR",
                ),
                name="seed_tray_generation_requires_tray",
            ),
        ),
    ]
