# Generated by Django 6.0.7 on 2026-08-09 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0025_seedtrayplanting_generation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specificplantlocation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="standing_plants",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="specificplantlocation",
            name="override_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="specificplantlocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("seed_tray_cell", "Seed Tray Cell"),
                    ("garden_square", "Garden Square"),
                    ("location", "Location"),
                ],
                max_length=20,
            ),
        ),
    ]
