# Generated by Django 6.0.7 on 2026-08-09 04:01

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0026_plant_stands_at_a_location"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkPlantOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_digest", models.CharField(editable=False, max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("germinate", "Germinate"),
                            ("move", "Move or transplant"),
                            ("ready", "Ready"),
                            ("retain", "Retain"),
                            ("donate", "Donate"),
                            ("fail", "Fail"),
                            ("cull", "Cull"),
                            ("finish_harvest", "Finish harvest"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "atomicity",
                    models.CharField(
                        choices=[
                            ("all_or_nothing", "All or nothing"),
                            ("eligible_only", "Eligible only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
                ("selection_source", models.JSONField(blank=True, default=dict)),
                ("action_payload", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="BulkPlantOperationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("skipped", "Skipped")],
                        max_length=12,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "lifecycle_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_operation_results",
                        to="plantings.plantlifecycleevent",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_operation_results",
                        to="plantings.specificplantlocation",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="plantings.bulkplantoperation",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_operation_results",
                        to="plantings.specificplant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["plant_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="bulkplantoperation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "idempotency_key"),
                name="bulk_plant_operation_idempotent",
            ),
        ),
        migrations.AddConstraint(
            model_name="bulkplantoperationresult",
            constraint=models.UniqueConstraint(
                fields=("operation", "plant"), name="bulk_plant_operation_result_unique"
            ),
        ),
    ]
