# Generated by Django 6.0.7 on 2026-08-10 23:05

import django.db.models.deletion
import django.utils.timezone
import workspaces.models
from django.conf import settings
from django.db import migrations, models


def backfill_plant_batches(apps, schema_editor):
    """Snapshot the batch already implied by each legacy tray-cell origin."""
    SpecificPlant = apps.get_model("plantings", "SpecificPlant")
    rows = SpecificPlant.objects.select_related(
        "cell_planting__seed_tray_planting"
    ).all()
    for plant in rows.iterator():
        plant.batch_id = plant.cell_planting.seed_tray_planting.batch_id
        plant.save(update_fields=["batch"])


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0027_bulkplantoperation_bulkplantoperationresult_and_more"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specificplant",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specific_plants",
                to="plantings.productionbatch",
            ),
        ),
        migrations.RunPython(backfill_plant_batches, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="specificplant",
            name="cell_planting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specific_plants",
                to="plantings.seedtraycellplanting",
            ),
        ),
        migrations.CreateModel(
            name="CohortOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("observe", "Observe"),
                            ("adjust", "Count adjustment"),
                            ("split", "Split"),
                            ("merge", "Merge"),
                            ("move", "Move"),
                            ("ready", "Ready"),
                            ("retain", "Retain"),
                            ("loss", "Loss"),
                            ("promote", "Promote"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PlantCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("growing", "Growing"),
                            ("available", "Available"),
                            ("retained", "Retained"),
                            ("depleted", "Depleted"),
                        ],
                        default="growing",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1, editable=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cohorts",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plant_cohorts",
                        to="locations.location",
                    ),
                ),
                (
                    "source_sowing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cohorts",
                        to="plantings.seedtrayplanting",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="CohortEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_before", models.PositiveIntegerField()),
                ("quantity_delta", models.IntegerField()),
                ("quantity_after", models.PositiveIntegerField()),
                (
                    "state_before",
                    models.CharField(
                        choices=[
                            ("growing", "Growing"),
                            ("available", "Available"),
                            ("retained", "Retained"),
                            ("depleted", "Depleted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "state_after",
                    models.CharField(
                        choices=[
                            ("growing", "Growing"),
                            ("available", "Available"),
                            ("retained", "Retained"),
                            ("depleted", "Depleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "location_after",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "location_before",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="plantings.cohortoperation",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="plantings.plantcohort",
                    ),
                ),
                (
                    "source_cohorts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lineage_events",
                        to="plantings.plantcohort",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
            },
        ),
        migrations.AddField(
            model_name="specificplant",
            name="promoted_from_cohort",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promoted_plants",
                to="plantings.plantcohort",
            ),
        ),
        migrations.AddConstraint(
            model_name="specificplant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cell_planting__isnull", False),
                        ("promoted_from_cohort__isnull", True),
                    ),
                    models.Q(
                        ("cell_planting__isnull", True),
                        ("promoted_from_cohort__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="specific_plant_exactly_one_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortoperation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "idempotency_key"),
                name="cohort_operation_workspace_idempotent",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantcohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="plant_cohort_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_after__gte", 0)),
                name="cohort_event_after_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortevent",
            constraint=models.UniqueConstraint(
                fields=("operation", "cohort"),
                name="cohort_event_operation_cohort_unique",
            ),
        ),
    ]
