# Generated by Django 6.0.7 on 2026-08-11

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import workspaces.models
from django.conf import settings
from django.db import migrations, models


STAGES = ('struck', 'rooted', 'potted_on', 'hardening', 'sale_ready')
GRADES = ('premium', 'standard', 'seconds')


def seed_catalogs(apps, schema_editor):  # pylint: disable=unused-argument
    Workspace = apps.get_model('workspaces', 'Workspace')
    GrowthStage = apps.get_model('plantings', 'GrowthStage')
    PlantGrade = apps.get_model('plantings', 'PlantGrade')
    for workspace in Workspace.objects.filter(mode='nursery'):
        for order, code in enumerate(STAGES):
            GrowthStage.objects.get_or_create(
                workspace=workspace, code=code,
                defaults={'name': code.replace('_', ' ').title(), 'display_order': order},
            )
        for order, code in enumerate(GRADES):
            PlantGrade.objects.get_or_create(
                workspace=workspace, code=code,
                defaults={'name': code.title(), 'display_order': order},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_container_footprint_m2_and_more'),
        ('plantings', '0028_cohort_inventory_foundation'),
        ('workspaces', '0002_workspace_override_tolerance_floor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('target_days', models.PositiveIntegerField(blank=True, null=True)),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['display_order', 'name', 'pk']},
        ),
        migrations.CreateModel(
            name='NurseryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_count', models.PositiveIntegerField(blank=True, null=True)),
                ('container_name', models.CharField(blank=True, default='', max_length=255)),
                ('container_size_label', models.CharField(blank=True, default='', max_length=64)),
                ('container_volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('container_footprint_m2', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))])),
                ('spread_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))])),
                ('root_condition', models.CharField(blank=True, default='', max_length=255)),
                ('expected_ready', models.DateField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('container_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursery_observations', to='inventory.inventoryitem')),
                ('corrects', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='plantings.nurseryobservation')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='plantings.growthstage')),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['occurred_at', 'pk']},
        ),
        migrations.CreateModel(
            name='NurseryObservationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursery_observation_targets', to='plantings.plantcohort')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='plantings.nurseryobservation')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursery_observation_targets', to='plantings.specificplant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['display_order', 'name', 'pk']},
        ),
        migrations.AddField(
            model_name='nurseryobservation', name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='plantings.plantgrade'),
        ),
        migrations.AddConstraint(model_name='growthstage', constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='growth_stage_workspace_code_unique')),
        migrations.AddConstraint(model_name='nurseryobservationtarget', constraint=models.CheckConstraint(condition=models.Q(models.Q(('cohort__isnull', True), ('plant__isnull', False)), models.Q(('cohort__isnull', False), ('plant__isnull', True)), _connector='OR'), name='nursery_observation_target_one_identity')),
        migrations.AddConstraint(model_name='nurseryobservationtarget', constraint=models.UniqueConstraint(condition=models.Q(('plant__isnull', False)), fields=('observation', 'plant'), name='nursery_observation_target_unique_plant')),
        migrations.AddConstraint(model_name='nurseryobservationtarget', constraint=models.UniqueConstraint(condition=models.Q(('cohort__isnull', False)), fields=('observation', 'cohort'), name='nursery_observation_target_unique_cohort')),
        migrations.AddConstraint(model_name='plantgrade', constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='plant_grade_workspace_code_unique')),
        migrations.RunPython(seed_catalogs, migrations.RunPython.noop),
    ]
