# Generated by Django 6.0.7 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_inputapplicationtarget_plant_cohort'),
        ('plantings', '0029_growthstage_nurseryobservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryobservation',
            name='input_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursery_observations', to='applications.inputapplication'),
        ),
    ]
