# Generated by Django 6.0.7 on 2026-08-11

from django.db import migrations, models


TARGET_DAYS = {
    'struck': 14,
    'rooted': 21,
    'potted_on': 21,
    'hardening': 7,
}


def seed_target_days(apps, schema_editor):
    GrowthStage = apps.get_model('plantings', 'GrowthStage')
    for code, target_days in TARGET_DAYS.items():
        GrowthStage.objects.filter(code=code, target_days=None).update(
            target_days=target_days,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('plantings', '0031_bulk_result_observation_and_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryobservation',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RunPython(seed_target_days, migrations.RunPython.noop),
    ]
