# Generated by Django 6.0.7 on 2026-08-11 07:39

import django.core.validators
import django.db.models.deletion
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_inventoryitem_container_footprint_m2_and_more"),
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0032_nurseryobservation_photo_url"),
        ("plants", "0002_workspace_ownership"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NurseryPlanDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("target_quantity", models.PositiveIntegerField()),
                ("ready_from", models.DateField()),
                ("ready_until", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("confirmed_order", "Confirmed order"),
                            ("forecast", "Forecast"),
                            ("manual", "Manual"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (10, "Low"),
                            (20, "Normal"),
                            (30, "High"),
                            (40, "Urgent"),
                        ],
                        default=20,
                    ),
                ),
                (
                    "customer_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "order_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_line_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursery_plan_demand",
                        to="plants.plantvariety",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "ready_from", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanningAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                (
                    "germination_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9")),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("seeds_per_cluster", models.PositiveIntegerField(default=1)),
                (
                    "tray_density",
                    models.PositiveIntegerField(
                        help_text="Seed clusters planned per tray."
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursery_planning_assumptions",
                        to="plants.plantvariety",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["variety__name", "-effective_from", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanningInputAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_plant",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "assumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs",
                        to="plantings.nurseryplanningassumption",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursery_planning_assumptions",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item__name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanningStageAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("lead_days", models.PositiveIntegerField()),
                (
                    "loss_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("0.999999")
                            ),
                        ],
                    ),
                ),
                (
                    "capacity_basis",
                    models.CharField(
                        choices=[
                            ("none", "Not tracked"),
                            ("trays", "Trays"),
                            ("containers", "Containers"),
                            ("plants", "Plants"),
                            ("area", "Area"),
                        ],
                        default="plants",
                        max_length=16,
                    ),
                ),
                (
                    "capacity_per_plant",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "assumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stages",
                        to="plantings.nurseryplanningassumption",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_stage_assumptions",
                        to="locations.location",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_assumptions",
                        to="plantings.growthstage",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_seeds", models.PositiveIntegerField()),
                ("required_clusters", models.PositiveIntegerField()),
                ("required_trays", models.PositiveIntegerField()),
                ("expected_finished", models.PositiveIntegerField()),
                ("sowing_date", models.DateField()),
                ("expected_ready_from", models.DateField()),
                ("expected_ready_until", models.DateField()),
                ("assumption_snapshot", models.JSONField(default=dict)),
                (
                    "assumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_requirements",
                        to="plantings.nurseryplanningassumption",
                    ),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_requirement",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "demand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement",
                        to="plantings.nurseryplandemand",
                    ),
                ),
            ],
            options={
                "ordering": ["sowing_date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("planned_date", models.DateField()),
                ("input_quantity", models.PositiveIntegerField()),
                ("expected_output", models.PositiveIntegerField()),
                (
                    "capacity_basis",
                    models.CharField(
                        choices=[
                            ("none", "Not tracked"),
                            ("trays", "Trays"),
                            ("containers", "Containers"),
                            ("plants", "Plants"),
                            ("area", "Area"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "capacity_required",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_milestones",
                        to="locations.location",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_milestones",
                        to="plantings.growthstage",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestones",
                        to="plantings.nurseryplanrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["planned_date", "sequence", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanInputRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=9, max_digits=24)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursery_plan_requirements",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inputs",
                        to="plantings.nurseryplanrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["item__name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("backward", "Backward from ready window"),
                            ("forward", "Forward from sowing date"),
                        ],
                        default="backward",
                        max_length=16,
                    ),
                ),
                ("sowing_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="plantings.nurseryproductionplan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "-version", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="NurseryPlanIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("seed", "Seed shortage"),
                            ("input", "Input shortage"),
                            ("tray", "Tray shortage"),
                            ("capacity", "Location capacity conflict"),
                            ("assumption", "Missing assumption"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "required_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=24, null=True
                    ),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=24, null=True
                    ),
                ),
                (
                    "demand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="plantings.nurseryplandemand",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="plantings.nurseryproductionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "pk"],
            },
        ),
        migrations.AddField(
            model_name="nurseryplandemand",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="demand_lines",
                to="plantings.nurseryproductionplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanningassumption",
            constraint=models.UniqueConstraint(
                fields=("workspace", "variety", "effective_from"),
                name="nursery_assumption_variety_effective_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanningassumption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("germination_rate__gt", 0), ("germination_rate__lte", 1)
                ),
                name="nursery_assumption_germination_rate_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanninginputassumption",
            constraint=models.UniqueConstraint(
                fields=("assumption", "item"), name="nursery_assumption_input_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanningstageassumption",
            constraint=models.UniqueConstraint(
                fields=("assumption", "sequence"),
                name="nursery_assumption_stage_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanningstageassumption",
            constraint=models.UniqueConstraint(
                fields=("assumption", "stage"), name="nursery_assumption_stage_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanningstageassumption",
            constraint=models.CheckConstraint(
                condition=models.Q(("loss_rate__gte", 0), ("loss_rate__lt", 1)),
                name="nursery_stage_loss_rate_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplanmilestone",
            constraint=models.UniqueConstraint(
                fields=("requirement", "sequence"),
                name="nursery_plan_milestone_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplaninputrequirement",
            constraint=models.UniqueConstraint(
                fields=("requirement", "item"),
                name="nursery_plan_input_requirement_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryproductionplan",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code", "version"),
                name="nursery_plan_workspace_code_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="nurseryplandemand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_line_reference", ""), _negated=True),
                fields=("plan", "source", "source_line_reference"),
                name="nursery_plan_demand_source_line_unique",
            ),
        ),
    ]
