# Generated by Django 6.0.7 on 2026-08-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0033_nurseryplandemand_nurseryplanningassumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurseryplaninputrequirement",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputs",
                to="plantings.nurseryplanrequirement",
            ),
        ),
        migrations.AlterField(
            model_name="nurseryplanissue",
            name="demand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="plantings.nurseryplandemand",
            ),
        ),
        migrations.AlterField(
            model_name="nurseryplanissue",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="plantings.nurseryproductionplan",
            ),
        ),
        migrations.AlterField(
            model_name="nurseryplanmilestone",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="plantings.nurseryplanrequirement",
            ),
        ),
        migrations.AlterField(
            model_name="nurseryplanrequirement",
            name="demand",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement",
                to="plantings.nurseryplandemand",
            ),
        ),
    ]
