# Generated by Django 6.0.7 on 2026-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0040_backward_bulk_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionbatch",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="A code left blank is filled in with a generated one on save.",
                max_length=64,
            ),
        ),
    ]
