# Generated by Django 6.0.7 on 2026-08-20 10:08

import django.core.validators
import django.db.models.deletion
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0007_gardenbed_kind"),
        ("locations", "0005_alter_location_location_type"),
        ("plantings", "0041_alter_productionbatch_code"),
        ("seeds", "0008_seedpacketquantityreconciliation_reversal_of"),
        ("supplies", "0003_supplier_is_system_default_and_more"),
        ("workspaces", "0006_workspace_garden_experience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GardenPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct_seed", "Direct seed"),
                            ("indoor_raised_seed", "Indoor-raised seed"),
                            ("purchased_plant", "Purchased plant"),
                            ("cutting", "Cutting"),
                            ("division", "Division"),
                            ("bulb_tuber_corm", "Bulb, tuber, or corm"),
                            ("bare_root", "Bare root"),
                            ("volunteer", "Volunteer"),
                            ("existing_unknown", "Existing or unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "tracking",
                    models.CharField(
                        choices=[
                            ("aggregate", "Aggregate crop or patch"),
                            ("individual", "Individual plants"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("quantity_is_approximate", models.BooleanField(default=False)),
                ("recorded_on", models.DateField()),
                (
                    "date_basis",
                    models.CharField(
                        choices=[
                            ("planted", "Planted"),
                            ("first_observed", "First observed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("date_is_approximate", models.BooleanField(default=False)),
                ("perennial", models.BooleanField(default=False)),
                (
                    "seed_quantity_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("finished_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["recorded_on", "pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="specificplant",
            name="specific_plant_exactly_one_origin",
        ),
        migrations.AddField(
            model_name="specificplant",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="garden_plantings",
                to="plantings.productionbatch",
            ),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="garden_square",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quick_plantings",
                to="garden.gardensquare",
            ),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quick_plantings",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="seed_packet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="garden_plantings",
                to="seeds.seedpacket",
            ),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="garden_plantings",
                to="supplies.supplier",
            ),
        ),
        migrations.AddField(
            model_name="gardenplanting",
            name="workspace",
            field=models.ForeignKey(
                default=workspaces.models.get_default_workspace_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="specificplant",
            name="garden_planting",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specific_plants",
                to="plantings.gardenplanting",
            ),
        ),
        migrations.AddConstraint(
            model_name="specificplant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cell_planting__isnull", False),
                        ("garden_planting__isnull", True),
                        ("promoted_from_cohort__isnull", True),
                    ),
                    models.Q(
                        ("cell_planting__isnull", True),
                        ("garden_planting__isnull", True),
                        ("promoted_from_cohort__isnull", False),
                    ),
                    models.Q(
                        ("cell_planting__isnull", True),
                        ("garden_planting__isnull", False),
                        ("promoted_from_cohort__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="specific_plant_exactly_one_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("garden_square__isnull", False), ("location__isnull", True)
                    ),
                    models.Q(
                        ("garden_square__isnull", True), ("location__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="garden_planting_exactly_one_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="garden_planting_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tracking", "aggregate"),
                    ("quantity_is_approximate", False),
                    _connector="OR",
                ),
                name="garden_individual_quantity_exact",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("seed_packet__isnull", True),
                        ("seed_quantity_used__isnull", True),
                    ),
                    models.Q(
                        ("seed_packet__isnull", False),
                        ("seed_quantity_used__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="garden_seed_packet_quantity_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("finished_on__isnull", True),
                    ("finished_on__gte", models.F("recorded_on")),
                    _connector="OR",
                ),
                name="garden_planting_finish_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tracking", "aggregate"),
                    ("finished_on__isnull", True),
                    _connector="OR",
                ),
                name="garden_individual_origin_not_finished",
            ),
        ),
    ]
