# Generated by Django 6.0.7 on 2026-08-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_report_indexes'),
        ('plantings', '0042_gardenplanting_and_more'),
        ('workspaces', '0006_workspace_garden_experience'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sowingstockposting',
            name='sowing_posting_exactly_one_planting',
        ),
        migrations.AddField(
            model_name='sowingstockposting',
            name='garden_planting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_postings', to='plantings.gardenplanting'),
        ),
        migrations.AddConstraint(
            model_name='sowingstockposting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('garden_planting__isnull', True), ('row_planting__isnull', False), ('square_planting__isnull', True), ('tray_planting__isnull', True)), models.Q(('garden_planting__isnull', True), ('row_planting__isnull', True), ('square_planting__isnull', False), ('tray_planting__isnull', True)), models.Q(('garden_planting__isnull', True), ('row_planting__isnull', True), ('square_planting__isnull', True), ('tray_planting__isnull', False)), models.Q(('garden_planting__isnull', False), ('row_planting__isnull', True), ('square_planting__isnull', True), ('tray_planting__isnull', True)), _connector='OR'), name='sowing_posting_exactly_one_planting'),
        ),
    ]
