# Generated by Django 5.2.5 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import workspaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantings', '0043_remove_sowingstockposting_sowing_posting_exactly_one_planting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenPlantingStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('finished', 'Finished'), ('failed', 'Failed'), ('corrected', 'Corrected')], max_length=12)),
                ('occurred_on', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='plantings.gardenplanting')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='plantings.gardenplantingstatusevent')),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['occurred_on', 'pk']},
        ),
        migrations.AddConstraint(
            model_name='gardenplantingstatusevent',
            constraint=models.CheckConstraint(
                condition=(models.Q(('event_type', 'corrected'), ('reversal_of__isnull', False)) | (models.Q(('event_type', 'corrected'), _negated=True) & models.Q(('reversal_of__isnull', True)))),
                name='garden_status_correction_has_target',
            ),
        ),
    ]
