# Generated by Django 6.1 on 2026-08-30 09:39

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0045_cohort_loss_cause"),
        ("workspaces", "0007_workspace_seller_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SowingGerminationClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("closed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sown_quantity", models.PositiveIntegerField()),
                ("observed_count", models.PositiveIntegerField()),
                ("ungerminated", models.PositiveIntegerField()),
                (
                    "loss_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("failed", "Failed"),
                            ("lost", "Lost during stocktake"),
                            ("culled", "Culled"),
                            ("donated", "Donated"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_reason", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="germination_closures",
                        to="plantings.seedtrayplanting",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reopened_at__isnull", True)),
                        fields=("sowing",),
                        name="one_open_germination_closure_per_sowing",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "ungerminated",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("sown_quantity"),
                                    "-",
                                    models.F("observed_count"),
                                ),
                            ),
                            models.Q(
                                ("observed_count__gte", models.F("sown_quantity")),
                                ("ungerminated", 0),
                            ),
                            _connector="OR",
                        ),
                        name="germination_closure_remainder_is_the_shortfall",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ungerminated__gt", 0),
                                models.Q(("loss_cause", ""), _negated=True),
                            ),
                            models.Q(("loss_cause", ""), ("ungerminated", 0)),
                            _connector="OR",
                        ),
                        name="germination_closure_cause_matches_remainder",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reopened_at__isnull", True), ("reopened_reason", "")
                            ),
                            models.Q(
                                ("reopened_at__isnull", False),
                                models.Q(("reopened_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="germination_closure_reopening_states_why",
                    ),
                ],
            },
        ),
    ]
