# Generated by Django 6.1 on 2026-09-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("plantings", "0046_sowinggerminationclosure"),
    ]

    operations = [
        migrations.AddField(
            model_name="specificplantlocation",
            name="container_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="standing_plants",
                to="inventory.inventoryunit",
            ),
        ),
        migrations.AlterField(
            model_name="specificplantlocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("seed_tray_cell", "Seed Tray Cell"),
                    ("garden_square", "Garden Square"),
                    ("location", "Location"),
                    ("container_unit", "Numbered Container"),
                ],
                max_length=20,
            ),
        ),
    ]
