# Generated by Django 6.1 on 2026-09-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0047_specificplantlocation_container_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohortoperation",
            name="action",
            field=models.CharField(
                choices=[
                    ("observe", "Observe"),
                    ("adjust", "Count adjustment"),
                    ("split", "Split"),
                    ("merge", "Merge"),
                    ("move", "Move"),
                    ("ready", "Ready"),
                    ("retain", "Retain"),
                    ("loss", "Loss"),
                    ("promote", "Promote"),
                    ("sold", "Sold"),
                    ("return", "Returned from an order"),
                ],
                max_length=16,
            ),
        ),
    ]
