# Generated by Django 6.1 on 2026-09-12 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0007_gardenbed_kind"),
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("plantings", "0051_coded_setting_catalog"),
        ("seedtrays", "0012_potfillresidualcorrection"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="specificplantlocation",
            name="plant_location_fill_needs_pot",
        ),
        migrations.AlterField(
            model_name="specificplantlocation",
            name="container_fill",
            field=models.ForeignKey(
                blank=True,
                help_text="The pot fill captured when this placement began.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plant_locations",
                to="seedtrays.seedtraygeneration",
            ),
        ),
        migrations.AddConstraint(
            model_name="specificplantlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("container_fill__isnull", True),
                    models.Q(
                        ("container_unit__isnull", False),
                        ("location_type", "container_unit"),
                    ),
                    models.Q(
                        ("container_unit__isnull", True),
                        ("location__isnull", False),
                        ("location_type", "location"),
                    ),
                    _connector="OR",
                ),
                name="plant_location_fill_needs_pot",
            ),
        ),
    ]
