# Generated by Django 6.1 on 2026-09-13 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0007_gardenbed_kind"),
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        (
            "plantings",
            "0052_remove_specificplantlocation_plant_location_fill_needs_pot_and_more",
        ),
        ("seedtrays", "0012_potfillresidualcorrection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specificplantlocation",
            name="numbered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specificplantlocation",
            name="numbered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="specificplantlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("numbered_at__isnull", True), ("numbered_by__isnull", True)
                    ),
                    models.Q(
                        ("container_fill__isnull", False),
                        ("container_unit__isnull", False),
                        ("location__isnull", True),
                        ("location_type", "container_unit"),
                        ("numbered_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="plant_location_numbering_needs_fill",
            ),
        ),
        migrations.AddConstraint(
            model_name="specificplantlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("numbered_at__isnull", True),
                    models.Q(
                        ("numbered_at__gte", models.F("started")),
                        models.Q(
                            ("ended__isnull", True),
                            ("ended__gte", models.F("numbered_at")),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="plant_location_numbering_within_stay",
            ),
        ),
    ]
