# Generated by Django 6.1 on 2026-09-19 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0053_counted_pot_numbering"),
        ("workspaces", "0008_assumption_variance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortoperation",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="plantings.cohortoperation",
            ),
        ),
        migrations.AlterField(
            model_name="cohortoperation",
            name="action",
            field=models.CharField(
                choices=[
                    ("observe", "Observe"),
                    ("adjust", "Count adjustment"),
                    ("split", "Split"),
                    ("merge", "Merge"),
                    ("move", "Move"),
                    ("ready", "Ready"),
                    ("retain", "Retain"),
                    ("loss", "Loss"),
                    ("promote", "Promote"),
                    ("sold", "Sold"),
                    ("return", "Returned from an order"),
                    ("corrected", "Loss corrected"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("action", "corrected"), ("reversal_of__isnull", False)),
                    models.Q(
                        models.Q(("action", "corrected"), _negated=True),
                        ("reversal_of__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cohort_operation_reversal_type",
            ),
        ),
    ]
