# Generated by Django 5.0.8 on 2024-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedpacket",
            name="empty",
            field=models.BooleanField(default=False),
        ),
    ]
