# Generated by Django 5.2.8 on 2025-11-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeds", "0002_seedpacket_empty"),
        ("supplies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seeds",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="supplies.supplier"
            ),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
