# Generated by Django 6.0.7 on 2026-08-02 00:02

import django.core.validators
import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_remove_stocklot_inventory_lot_positive_initial_quantity_and_more",
        ),
        ("seeds", "0004_workspace_ownership"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seedpacket",
            name="stock_lot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seed_packet",
                to="inventory.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="seedpacket",
            name="storage_location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seed_packet",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="seeds",
            name="inventory_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seed_catalog",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.CreateModel(
            name="SeedPacketQuantityReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_certainty",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("estimated", "Estimated"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reconstructed_initial_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seed_packet_reconciliation",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quantity_reconciliations",
                        to="seeds.seedpacket",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SeedPacketReceiptDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "packet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_draft",
                        to="seeds.seedpacket",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seed_packet_draft",
                        to="inventory.stockreceipt",
                    ),
                ),
                (
                    "seeds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packet_receipt_drafts",
                        to="seeds.seeds",
                    ),
                ),
                (
                    "storage_location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seed_packet_draft",
                        to="inventory.inventorylocation",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-pk"],
            },
        ),
    ]
