# Generated by Django 6.1 on 2026-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seeds", "0008_seedpacketquantityreconciliation_reversal_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="seeds",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Retired records stay readable everywhere they are already recorded, but are no longer offered as choices.",
            ),
        ),
    ]
