# Generated by Django 6.0.7 on 2026-08-12 01:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0034_alter_nurseryplaninputrequirement_requirement_and_more"),
        ("plants", "0002_workspace_ownership"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkTaskRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=160)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("germination_check", "Germination check"),
                            ("watering", "Watering"),
                            ("feeding", "Feeding"),
                            ("thinning", "Thinning"),
                            ("spacing", "Spacing"),
                            ("potting_on", "Potting on"),
                            ("hardening", "Hardening"),
                            ("ready_review", "Ready-date review"),
                            ("harvest_review", "Harvest review"),
                            ("stocktake", "Stocktake"),
                            ("order_picking", "Order picking"),
                            ("stage_review", "Stage review"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("sowing_germination", "Expected sowing germination"),
                            ("plan_milestone", "Approved plan milestone"),
                            ("stage_age", "Current stage target age"),
                            ("expected_ready", "Recorded expected-ready date"),
                            ("sowing_maturity", "Expected sowing maturity"),
                            ("calendar", "Recurring calendar work"),
                        ],
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=20)),
                ("due_start_offset_days", models.IntegerField(default=0)),
                ("due_end_offset_days", models.IntegerField(default=0)),
                ("local_due_time", models.TimeField(default="09:00")),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Does not repeat"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("weekdays", models.JSONField(blank=True, default=list)),
                (
                    "season_start",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("season_end", models.CharField(blank=True, default="", max_length=5)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_task_rules",
                        to="locations.location",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_task_rules",
                        to="plantings.growthstage",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_task_rules",
                        to="plants.plantvariety",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WorkTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "Manual"), ("generated", "Generated")],
                        max_length=16,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("germination_check", "Germination check"),
                            ("watering", "Watering"),
                            ("feeding", "Feeding"),
                            ("thinning", "Thinning"),
                            ("spacing", "Spacing"),
                            ("potting_on", "Potting on"),
                            ("hardening", "Hardening"),
                            ("ready_review", "Ready-date review"),
                            ("harvest_review", "Harvest review"),
                            ("stocktake", "Stocktake"),
                            ("order_picking", "Order picking"),
                            ("stage_review", "Stage review"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("priority", models.PositiveSmallIntegerField(default=20)),
                ("due_start", models.DateTimeField()),
                ("due_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("snoozed", "Snoozed"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                ("recurrence", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="following_occurrences",
                        to="work.worktask",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="work.worktaskrule",
                    ),
                ),
            ],
            options={
                "ordering": ["due_end", "-priority", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WorkTaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("reason", models.TextField(blank=True, default="")),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="work.worktask",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("task", "idempotency_key"),
                        name="work_history_task_idempotent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkTaskLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("target", "Target"), ("result", "Result")],
                        max_length=12,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("label", models.CharField(max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=255)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="work.worktask",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "content_type_id", "object_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "role", "content_type", "object_id"),
                        name="work_task_link_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="worktaskrule",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"), name="work_rule_workspace_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="worktaskrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_end_offset_days__gte", models.F("due_start_offset_days"))
                ),
                name="work_rule_due_offsets_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="worktask",
            index=models.Index(
                fields=["workspace", "status", "due_end"],
                name="work_queue_status_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="worktask",
            index=models.Index(
                fields=["workspace", "assignee"], name="work_queue_assignee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="worktask",
            constraint=models.UniqueConstraint(
                fields=("workspace", "key"), name="work_task_workspace_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="worktask",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_end__gte", models.F("due_start"))),
                name="work_task_due_window_ordered",
            ),
        ),
    ]
