# Generated by Django 6.0.7 on 2026-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_seed_default_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("germination_check", "Germination check"),
                    ("watering", "Watering"),
                    ("feeding", "Feeding"),
                    ("thinning", "Thinning"),
                    ("spacing", "Spacing"),
                    ("potting_on", "Potting on"),
                    ("hardening", "Hardening"),
                    ("ready_review", "Ready-date review"),
                    ("harvest_review", "Harvest review"),
                    ("stocktake", "Stocktake"),
                    ("order_picking", "Order picking"),
                    ("stage_review", "Stage review"),
                    ("health_inspection", "Health inspection"),
                    ("treatment_follow_up", "Treatment follow-up"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="worktaskrule",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("germination_check", "Germination check"),
                    ("watering", "Watering"),
                    ("feeding", "Feeding"),
                    ("thinning", "Thinning"),
                    ("spacing", "Spacing"),
                    ("potting_on", "Potting on"),
                    ("hardening", "Hardening"),
                    ("ready_review", "Ready-date review"),
                    ("harvest_review", "Harvest review"),
                    ("stocktake", "Stocktake"),
                    ("order_picking", "Order picking"),
                    ("stage_review", "Stage review"),
                    ("health_inspection", "Health inspection"),
                    ("treatment_follow_up", "Treatment follow-up"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="worktaskrule",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("sowing_germination", "Expected sowing germination"),
                    ("plan_milestone", "Approved plan milestone"),
                    ("stage_age", "Current stage target age"),
                    ("expected_ready", "Recorded expected-ready date"),
                    ("sowing_maturity", "Expected sowing maturity"),
                    ("calendar", "Recurring calendar work"),
                    ("health_follow_up", "Health follow-up due"),
                ],
                max_length=32,
            ),
        ),
    ]
