# Generated by Django 6.1 on 2026-09-12 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0009_assumption_variance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worktaskrule",
            options={"ordering": ["display_order", "name", "pk"]},
        ),
        migrations.AddField(
            model_name="worktaskrule",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worktaskrule",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record this duplicate was merged into. It keeps its own identity so anything written against it still resolves.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="work.worktaskrule",
            ),
        ),
        migrations.AlterField(
            model_name="worktaskrule",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Retired records stay readable everywhere they are already recorded, but are no longer offered as choices.",
            ),
        ),
        migrations.AlterField(
            model_name="worktaskrule",
            name="code",
            field=models.CharField(
                help_text="The stable handle everything else names this setting by. It is written once; a wrong one is corrected by merging into the record that carries the right one.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="worktaskrule",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
