"""
Django settings for gp project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import importlib
import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Import other settings. GP_SITE_SETTINGS names the module holding the
# site-specific settings, so the same checkout can run the test suite against
# PostgreSQL (gp.ci_settings) without disturbing gp/local_settings.py.
SITE_SETTINGS_MODULE = os.environ.get("GP_SITE_SETTINGS", "gp.local_settings")

try:
    _site_settings = importlib.import_module(SITE_SETTINGS_MODULE)
except ImportError as error:
    raise ImproperlyConfigured(
        f"Unable to import site settings module {SITE_SETTINGS_MODULE!r}. "
        "Run setup-venv.sh or correct GP_SITE_SETTINGS."
    ) from error

globals().update(
    {name: value for name, value in vars(_site_settings).items() if name.isupper()}
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY_PATH = BASE_DIR / "gp" / "secretkey.txt"

try:
    SECRET_KEY = SECRET_KEY_PATH.read_text(encoding="utf-8").strip()
except OSError as error:
    raise ImproperlyConfigured(
        f"Unable to read Django secret key from {SECRET_KEY_PATH}. "
        "Run setup-venv.sh or provide a readable key file."
    ) from error

if not SECRET_KEY:
    raise ImproperlyConfigured(
        f"Django secret key file {SECRET_KEY_PATH} is empty. "
        "Populate it with a securely generated key before starting the application."
    )

# Application definition

INSTALLED_APPS = [
    "attachments",
    "workspaces",
    "locations",
    "inventory",
    "plants",
    "seeds",
    "garden",
    "plantings",
    "supplies",
    "frontend",
    "seedtrays",
    "applications",
    "costing",
    "sales",
    "billing",
    "purchasing",
    "bookkeeping",
    "labels",
    "work",
    "health",
    "reporting",
    "tax",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "gp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gp.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Uploaded photographs are deliberately outside the public static tree. They
# are opened only by the authenticated attachment views, never by a MEDIA_URL.
ATTACHMENT_ROOT = Path(globals().get(
    "ATTACHMENT_ROOT", BASE_DIR / "var" / "attachments",
))
ATTACHMENT_MAX_BYTES = globals().get("ATTACHMENT_MAX_BYTES", 15 * 1024 * 1024)
ATTACHMENT_MAX_PIXELS = globals().get("ATTACHMENT_MAX_PIXELS", 40_000_000)
ATTACHMENT_ARCHIVE_MAX_BYTES = globals().get(
    "ATTACHMENT_ARCHIVE_MAX_BYTES", 1024 * 1024 * 1024,
)
ATTACHMENT_ARCHIVE_MAX_EXPANDED_BYTES = globals().get(
    "ATTACHMENT_ARCHIVE_MAX_EXPANDED_BYTES", 2 * 1024 * 1024 * 1024,
)
ATTACHMENT_ARCHIVE_MAX_ENTRIES = globals().get(
    "ATTACHMENT_ARCHIVE_MAX_ENTRIES", 10_000,
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Reports which tests a backend could not run instead of leaving the reader to
# work out what "OK (skipped=21)" cost them.
TEST_RUNNER = "gp.test_runner.GardenTestRunner"

LOGIN_REDIRECT_URL = "/"

# The initial deployment deliberately exposes one shared workspace to every
# authenticated user. Tests may create other workspaces to verify isolation.
CURRENT_WORKSPACE_ID = globals().get("CURRENT_WORKSPACE_ID", 1)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
}
