# Generated by Django 5.0.6 on 2024-07-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GardenArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=1024)),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GardenBed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=1024)),
                ("placement_x", models.IntegerField()),
                ("placement_y", models.IntegerField()),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garden.gardenarea",
                    ),
                ),
            ],
        ),
    ]
