# Generated by Django 5.0.6 on 2024-07-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GardenRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=1024)),
                ("placement_x", models.IntegerField()),
                ("placement_y", models.IntegerField()),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garden.gardenbed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GardenSquare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=1024)),
                ("placement_x", models.IntegerField()),
                ("placement_y", models.IntegerField()),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="garden.gardenbed",
                    ),
                ),
            ],
        ),
    ]
