# Generated by Django 6.0.6 on 2026-07-18 07:29

from django.db import migrations, models


GEOMETRY_MODELS = (
    ('GardenArea', False),
    ('GardenBed', True),
    ('GardenRow', True),
    ('GardenSquare', True),
)


def describe_rows(queryset):
    """Return a bounded description of rows that failed the audit."""
    count = queryset.count()
    row_ids = list(queryset.order_by('pk').values_list('pk', flat=True)[:20])
    suffix = '' if count <= len(row_ids) else f' (first 20 of {count})'
    return f'{row_ids}{suffix}'


def audit_garden_geometry(apps, _schema_editor):
    """Stop deployment when existing geometry cannot satisfy the constraints."""
    problems = []
    for model_name, has_placement in GEOMETRY_MODELS:
        model = apps.get_model('garden', model_name)
        invalid_sizes = model.objects.filter(
            models.Q(size_x__lt=1) | models.Q(size_y__lt=1)
        )
        if invalid_sizes.count():
            problems.append(
                f'{model_name} size IDs: {describe_rows(invalid_sizes)}'
            )

        if has_placement:
            invalid_placements = model.objects.filter(
                models.Q(placement_x__lt=0) | models.Q(placement_y__lt=0)
            )
            if invalid_placements.count():
                problems.append(
                    f'{model_name} placement IDs: '
                    f'{describe_rows(invalid_placements)}'
                )

    if problems:
        raise RuntimeError(
            'Garden geometry audit failed. Repair invalid sizes or placements '
            f'before retrying the migration: {"; ".join(problems)}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0003_validate_garden_geometry"),
    ]

    operations = [
        migrations.RunPython(audit_garden_geometry, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="gardenarea",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_x__gte", 1), ("size_y__gte", 1)),
                name="area_size_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenbed",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_x__gte", 1), ("size_y__gte", 1)),
                name="bed_size_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenbed",
            constraint=models.CheckConstraint(
                condition=models.Q(("placement_x__gte", 0), ("placement_y__gte", 0)),
                name="bed_placement_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_x__gte", 1), ("size_y__gte", 1)),
                name="row_size_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardenrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("placement_x__gte", 0), ("placement_y__gte", 0)),
                name="row_placement_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardensquare",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_x__gte", 1), ("size_y__gte", 1)),
                name="square_size_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="gardensquare",
            constraint=models.CheckConstraint(
                condition=models.Q(("placement_x__gte", 0), ("placement_y__gte", 0)),
                name="square_placement_gte_0",
            ),
        ),
    ]
