# Generated by Django 6.0.7 on 2026-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0006_gardengeometryconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="gardenbed",
            name="kind",
            field=models.CharField(
                choices=[
                    ("in_ground", "In-ground bed"),
                    ("raised", "Raised bed"),
                    ("container", "Container or planter"),
                ],
                default="in_ground",
                max_length=16,
            ),
        ),
    ]
