# Generated by Django 6.0.7 on 2026-08-01 09:24

import django.core.validators
import django.db.models.deletion
import workspaces.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, default="", max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("growing_media", "Growing media"),
                            ("fertilizer_treatment", "Fertilizer or treatment"),
                            ("label", "Label"),
                            ("packaging", "Packaging"),
                            ("pot_container", "Pot or container"),
                            ("tray", "Tray"),
                            ("other", "Other physical input"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "tracking_mode",
                    models.CharField(
                        choices=[
                            ("lot", "Lot controlled"),
                            ("serialized", "Serialized"),
                        ],
                        default="lot",
                        max_length=16,
                    ),
                ),
                (
                    "default_usage_basis",
                    models.CharField(
                        choices=[
                            ("cell_volume", "Cell volume"),
                            ("surface_area", "Surface-area rate"),
                            ("per_unit", "Per plant or item"),
                            ("fixed", "Fixed quantity"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "default_usage_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        help_text="Base-unit quantity consumed per usage-rate unit.",
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "usage_rate_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "default_fixed_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        help_text="Base-unit quantity suggested for fixed usage.",
                        max_digits=24,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "stock_history_started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ItemUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=9,
                        help_text="Quantity of the item base unit represented by one package unit.",
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_conversions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["label", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("workspace", "sku"),
                name="inventory_item_workspace_sku_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_usage_rate__isnull", True),
                    ("default_usage_rate__gt", 0),
                    _connector="OR",
                ),
                name="inventory_item_positive_usage_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_fixed_quantity__isnull", True),
                    ("default_fixed_quantity__gt", 0),
                    _connector="OR",
                ),
                name="inventory_item_positive_fixed_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunitconversion",
            constraint=models.UniqueConstraint(
                fields=("item", "label"), name="inventory_conversion_item_label_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunitconversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("multiplier__gt", 0)),
                name="inventory_conversion_positive_multiplier",
            ),
        ),
    ]
