# Generated by Django 6.0.7 on 2026-08-01 11:02

import django.core.validators
import django.db.models.deletion
import inventory.models
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("supplies", "0002_supplier_workspace"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("receiving", "Receiving"),
                            ("storage", "Storage"),
                            ("growing", "Nursery or growing area"),
                            ("dispatch", "Customer dispatch"),
                            ("quarantine", "Quarantine"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        default=inventory.models.generate_lot_identifier, max_length=64
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("receipt", "Supplier receipt"),
                            ("opening", "Opening balance"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "supplier_lot_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("received_on", models.DateField()),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "initial_base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "acquisition_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "base_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        max_digits=30,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["item__name", "identifier", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("receipt", "Receipt"),
                            ("consumption", "Consumption"),
                            ("transfer", "Transfer"),
                            ("adjustment_gain", "Adjustment gain"),
                            ("adjustment_loss", "Adjustment loss"),
                            ("waste", "Waste"),
                            ("sale", "Sale"),
                            ("customer_return", "Customer return"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["occurred_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StockReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("received_date", models.DateField()),
                (
                    "supplier_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "currency_code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a three-letter uppercase ISO 4217 currency code.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("tax_recoverable", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reversed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-received_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="StockReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_lot_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "line_cost_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Stocktake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("counted_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reversed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-counted_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="StocktakeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "counted_base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_base_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=24, null=True
                    ),
                ),
                (
                    "variance_base_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=24, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="reorder_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                help_text="Optional low-stock threshold in the item base unit.",
                max_digits=24,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reorder_level__isnull", True),
                    ("reorder_level__gte", 0),
                    _connector="OR",
                ),
                name="inventory_item_nonnegative_reorder_level",
            ),
        ),
        migrations.AddField(
            model_name="inventorylocation",
            name="workspace",
            field=models.ForeignKey(
                default=workspaces.models.get_default_workspace_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_lots",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="workspace",
            field=models.ForeignKey(
                default=workspaces.models.get_default_workspace_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_stock_movements",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="inventory.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_stock_movements",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="workspace",
            field=models.ForeignKey(
                default=workspaces.models.get_default_workspace_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_receipts",
                to="supplies.supplier",
            ),
        ),
        migrations.AddField(
            model_name="stockreceipt",
            name="workspace",
            field=models.ForeignKey(
                default=workspaces.models.get_default_workspace_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stockreceiptline",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="stockreceiptline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="stockreceiptline",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.stockreceipt",
            ),
        ),
        migrations.AddField(
            model_name="stockreceiptline",
            name="unit_conversion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="inventory.itemunitconversion",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="receipt_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.stockreceiptline",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="receipt_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_lot",
                to="inventory.stockreceiptline",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="workspace",
            field=models.ForeignKey(
                default=workspaces.models.get_default_workspace_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stocktake_lines",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stocktake_lines",
                to="inventory.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="stocktake",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.stocktake",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="unit_conversion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stocktake_lines",
                to="inventory.itemunitconversion",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stocktake_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.stocktakeline",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorylocation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"),
                name="inventory_location_workspace_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="inventory_receipt_line_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", 0)),
                name="inventory_receipt_line_positive_base_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_cost_ex_tax__gte", 0)),
                name="inventory_receipt_line_nonnegative_cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.UniqueConstraint(
                fields=("workspace", "item", "identifier"),
                name="inventory_lot_workspace_item_identifier_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(("initial_base_quantity__gt", 0)),
                name="inventory_lot_positive_initial_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acquisition_total__isnull", True),
                    ("acquisition_total__gte", 0),
                    _connector="OR",
                ),
                name="inventory_lot_nonnegative_acquisition_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_unit_cost__isnull", True),
                    ("base_unit_cost__gte", 0),
                    _connector="OR",
                ),
                name="inventory_lot_nonnegative_unit_cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.UniqueConstraint(
                fields=("stocktake", "lot", "location"),
                name="inventory_stocktake_lot_location_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_quantity__gte", 0)),
                name="inventory_stocktake_nonnegative_counted_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_base_quantity__gte", 0)),
                name="inventory_stocktake_nonnegative_base_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="inventory_movement_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__isnull", True),
                    ("destination__isnull", True),
                    models.Q(("source", models.F("destination")), _negated=True),
                    _connector="OR",
                ),
                name="inventory_movement_distinct_locations",
            ),
        ),
    ]
