# Generated by Django 6.0.7 on 2026-08-02 00:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorylocation_stocklot_stockmovement_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stocklot",
            name="inventory_lot_positive_initial_quantity",
        ),
        migrations.RemoveConstraint(
            model_name="stockreceiptline",
            name="inventory_receipt_line_positive_quantity",
        ),
        migrations.RemoveConstraint(
            model_name="stockreceiptline",
            name="inventory_receipt_line_positive_base_quantity",
        ),
        migrations.AddField(
            model_name="stocklot",
            name="quantity_certainty",
            field=models.CharField(
                choices=[
                    ("exact", "Exact"),
                    ("estimated", "Estimated"),
                    ("unknown", "Unknown"),
                ],
                default="exact",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stockreceiptline",
            name="quantity_certainty",
            field=models.CharField(
                choices=[
                    ("exact", "Exact"),
                    ("estimated", "Estimated"),
                    ("unknown", "Unknown"),
                ],
                default="exact",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="inventorylocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("receiving", "Receiving"),
                    ("storage", "Storage"),
                    ("growing", "Nursery or growing area"),
                    ("dispatch", "Customer dispatch"),
                    ("quarantine", "Quarantine"),
                    ("adjustment", "Adjustment"),
                    ("seed_packet", "Seed packet"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stocklot",
            name="initial_base_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=24,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-9"))],
            ),
        ),
        migrations.AlterField(
            model_name="stocklot",
            name="received_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockreceiptline",
            name="base_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=24,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-9"))],
            ),
        ),
        migrations.AlterField(
            model_name="stockreceiptline",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=24,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-9"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("initial_base_quantity__isnull", True),
                    ("initial_base_quantity__gt", 0),
                    _connector="OR",
                ),
                name="inventory_lot_positive_initial_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__isnull", True), ("quantity__gt", 0), _connector="OR"
                ),
                name="inventory_receipt_line_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_quantity__isnull", True),
                    ("base_quantity__gt", 0),
                    _connector="OR",
                ),
                name="inventory_receipt_line_positive_base_quantity",
            ),
        ),
    ]
