# Generated by Django 6.0.7 on 2026-08-02 03:13

import django.core.validators
import django.db.models.deletion
import inventory.models
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stocklot_inventory_lot_positive_initial_quantity_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnitReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_cost', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(default=inventory.models.generate_asset_code, max_length=64)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency_code', models.CharField(max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serialized_units', to='inventory.inventorylocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_units', to='inventory.inventoryitem')),
                ('source_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_units', to='inventory.stocklot')),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['asset_code', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryunit'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit__isnull', True), ('quantity', 1), _connector='OR'), name='inventory_movement_serialized_quantity_one'),
        ),
        migrations.AddField(
            model_name='inventoryunitreconciliation',
            name='movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unit_opening_reconciliation', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='inventoryunitreconciliation',
            name='recorded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryunitreconciliation',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_reconciliation', to='inventory.inventoryunit'),
        ),
        migrations.AddField(
            model_name='inventoryunitreconciliation',
            name='workspace',
            field=models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunit',
            constraint=models.UniqueConstraint(fields=('workspace', 'asset_code'), name='inventory_unit_workspace_asset_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunit',
            constraint=models.CheckConstraint(condition=models.Q(('acquisition_cost__isnull', True), ('acquisition_cost__gte', 0), _connector='OR'), name='inventory_unit_nonnegative_acquisition_cost'),
        ),
    ]
