# Generated by Django 6.0.7 on 2026-08-11

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_point_stock_at_the_locations_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='container_footprint_m2',
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))],
            ),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='container_size_label',
            field=models.CharField(
                blank=True, default='',
                help_text='Commercial container size, for example P9 or 2 L.',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='container_volume_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
