# Generated by Django 6.1 on 2026-08-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_report_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreceipt",
            name="settled_on",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
