# Generated by Django 6.1 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_remove_receipt_tax_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="tracking_mode",
            field=models.CharField(
                choices=[
                    ("lot", "Lot controlled"),
                    ("serialized", "Serialized"),
                    ("mixed", "Lot controlled, individually numberable"),
                ],
                default="lot",
                max_length=16,
            ),
        ),
    ]
