# Generated by Django 6.1 on 2026-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_inventoryunit_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktaketarget",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("lot", "Consumable lot"),
                    ("seed_packet", "Seed packet"),
                    ("tray", "Serialized tray"),
                    ("unit", "Numbered unit"),
                    ("cohort", "Plant cohort"),
                    ("plant", "Individual plant"),
                ],
                max_length=16,
            ),
        ),
    ]
