# Generated by Django 6.1 on 2026-09-21 10:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stocktaketarget_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='freight_acquisition_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Inbound freight in receipt currency, excluding recoverable tax and amounts already in the goods lines.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='allocated_freight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
