# Generated by Django 5.2.8 on 2025-12-29 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeedTrayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("height", models.PositiveIntegerField()),
                ("x_size", models.PositiveIntegerField()),
                ("y_size", models.PositiveIntegerField()),
                ("x_cells", models.PositiveIntegerField()),
                ("y_cells", models.PositiveIntegerField()),
                (
                    "cell_size_ml",
                    models.PositiveIntegerField(
                        help_text="Volume of each cell in milliliters"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeedTray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seedtrays.seedtraymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeedTrayCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_position", models.PositiveIntegerField()),
                ("y_position", models.PositiveIntegerField()),
                (
                    "tray",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seedtrays.seedtray",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tray", "x_position", "y_position"),
                        name="unique_cell_per_tray",
                    )
                ],
            },
        ),
    ]
