# Generated by Django 6.0.3 on 2026-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seedtrays", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedtray",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
