# Generated by Django 6.0.7 on 2026-08-08 01:59

import django.core.validators
import django.db.models.deletion
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_stockreceipt_price_includes_tax"),
        ("plantings", "0024_harvest"),
        ("seedtrays", "0004_seedtray_inventory_unit_seedtraymodel_inventory_item"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedTrayGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("operator", "Opened by an operator"),
                            ("legacy", "Migrated from existing sowings"),
                        ],
                        default="operator",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[("none", "None"), ("needs_review", "Needs review")],
                        default="none",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "review_details",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("opened_at", models.DateTimeField()),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "close_reason",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tray",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generations",
                        to="seedtrays.seedtray",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["tray", "-sequence", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SeedTrayGenerationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                            ("reviewed", "Reviewed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="seedtrays.seedtraygeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SeedTrayGenerationResidual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("media", "Growing media"), ("seed", "Unsown seed")],
                        max_length=16,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("waste", "Discarded as waste"),
                            ("reclaimed", "Reclaimed into stock"),
                            ("removed", "Removed and not kept"),
                            ("returned", "Returned to stock"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=30, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="residuals",
                        to="seedtrays.seedtraygeneration",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tray_generation_residuals",
                        to="inventory.stocklot",
                    ),
                ),
                (
                    "movement",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tray_generation_residual",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "sowing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_residuals",
                        to="plantings.seedtrayplanting",
                    ),
                ),
            ],
            options={
                "ordering": ["generation", "kind", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"),
                name="tray_generation_workspace_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.UniqueConstraint(
                fields=("tray", "sequence"), name="tray_generation_tray_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("tray",),
                name="tray_generation_single_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("closed_at__isnull", True), ("status", "open")),
                    models.Q(("closed_at__isnull", False), ("status", "closed")),
                    _connector="OR",
                ),
                name="tray_generation_close_stamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="tray_generation_sequence_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygenerationresidual",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", 0)),
                name="tray_generation_residual_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygenerationresidual",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("disposition__in", ["waste", "reclaimed"]),
                        ("kind", "media"),
                        ("sowing__isnull", True),
                    ),
                    models.Q(
                        ("disposition__in", ["removed", "returned"]),
                        ("kind", "seed"),
                        ("sowing__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="tray_generation_residual_kind_disposition",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygenerationresidual",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("disposition__in", ["reclaimed", "returned"])),
                    models.Q(
                        ("disposition__in", ["waste", "removed"]),
                        ("movement__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tray_generation_residual_movement",
            ),
        ),
    ]
