# Generated by Django 6.1 on 2026-09-07 08:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_nontray_rollback(apps, schema_editor):
    """An older tray-only schema cannot preserve pot-fill identities."""
    fills = apps.get_model('seedtrays', 'SeedTrayGeneration')
    if fills.objects.using(schema_editor.connection.alias).filter(tray__isnull=True).exists():
        raise RuntimeError('Cannot reverse container-fill targets while non-tray fills exist.')


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("seedtrays", "0008_generation_inventory_unit"),
        ("workspaces", "0008_assumption_variance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seedtraygeneration",
            name="container_count",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="seedtraygeneration",
            name="source_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_fills",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="seedtraygeneration",
            name="stock_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_fills",
                to="inventory.stocklot",
            ),
        ),
        migrations.AlterField(
            model_name="seedtraygeneration",
            name="inventory_unit",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_fills",
                to="inventory.inventoryunit",
            ),
        ),
        migrations.AlterField(
            model_name="seedtraygeneration",
            name="tray",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generations",
                to="seedtrays.seedtray",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("container_count", 1),
                        ("inventory_unit__isnull", False),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("source_location__isnull", False),
                        ("stock_lot__isnull", False),
                        ("tray__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="container_fill_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(("container_count__gte", 1)),
                name="container_fill_positive_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.UniqueConstraint(
                fields=("inventory_unit", "sequence"),
                name="container_fill_unit_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("inventory_unit",),
                name="container_fill_single_open_unit",
            ),
        ),
        # First on reversal, before any field carrying the new history is lost.
        migrations.RunPython(migrations.RunPython.noop, refuse_nontray_rollback),
    ]
