# Generated by Django 6.1 on 2026-09-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seedtrays", "0009_container_fill_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedtraymodel",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record that supersedes this one. Everything already recorded stays here, because it was recorded against what this one said.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replaces",
                to="seedtrays.seedtraymodel",
            ),
        ),
    ]
