# Generated by Django 6.1 on 2026-09-10 08:28

from django.conf import settings
from django.db import migrations, models


def refuse_frozen_share_rollback(apps, schema_editor):
    """A share basis was fixed by departures that cannot be replayed."""
    fills = apps.get_model('seedtrays', 'SeedTrayGeneration')
    if fills.objects.using(schema_editor.connection.alias).filter(
        plant_share_count__isnull=False,
    ).exists():
        raise RuntimeError('Cannot reverse the pot share basis while frozen plant shares exist.')


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("seedtrays", "0010_replace_tray_models"),
        ("workspaces", "0008_assumption_variance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seedtraygeneration",
            name="plant_share_count",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="Numbered-pot participants fixed at the first recorded departure.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="seedtraygeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plant_share_count__isnull", True),
                    models.Q(
                        ("inventory_unit__isnull", False),
                        ("plant_share_count__gte", 1),
                        ("tray__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="pot_fill_positive_share_count",
            ),
        ),
        # First on reversal, before the frozen denominators are dropped. The
        # guard in 0009 comes too late: this migration is unapplied ahead of it.
        migrations.RunPython(migrations.RunPython.noop, refuse_frozen_share_rollback),
    ]
