# Generated by Django 6.1 on 2026-09-12 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seedtrays", "0011_numbered_fill_share_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotFillResidualCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pot_residual_corrections",
                        to="seedtrays.seedtraygenerationevent",
                    ),
                ),
                (
                    "residual",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pot_correction",
                        to="seedtrays.seedtraygenerationresidual",
                    ),
                ),
            ],
        ),
    ]
