# Generated by Django 6.1 on 2026-09-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedtrays', '0012_potfillresidualcorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedtraygenerationevent',
            name='event_type',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('dispatched', 'Dispatched with its plants'), ('reopened', 'Reopened'), ('reviewed', 'Reviewed')], max_length=16),
        ),
    ]
