# Generated by Django 6.1 on 2026-08-22 04:52

import django.core.validators
import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0006_workspace_garden_experience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GstRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered",
                    models.BooleanField(
                        help_text="Whether the workspace is GST registered from this date. A false row records a deregistration or cessation."
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="The first day this arrangement applies to."
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The nine-digit IRD/GST number the registration is held under.",
                        max_length=11,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payments", "Payments"),
                            ("invoice", "Invoice"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="",
                        help_text="The accounting basis in force from this date.",
                        max_length=16,
                    ),
                ),
                (
                    "filing_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("two_monthly", "Two-monthly"),
                            ("six_monthly", "Six-monthly"),
                        ],
                        default="",
                        help_text="How often a return is filed from this date.",
                        max_length=16,
                    ),
                ),
                (
                    "period_anchor_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="A month a taxable period ends in, from 1 through 12. This is how Inland Revenue names a cycle: two-monthly filing ends in either the odd or the even months, and six-monthly in March/September, April/October, or May/November. Ignored by monthly filing.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "taxable_activity_start",
                    models.DateField(
                        blank=True,
                        help_text="When the taxable activity itself began, which may be well before the registration and is what the turnover threshold is measured from.",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why the arrangement changed, in the operator's own words.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        help_text="The row this one corrects. A superseded row stays in the table and stops contributing to what was in force.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="tax.gstregistration",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["effective_from", "pk"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "effective_from"],
                        name="gst_registration_date_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("basis__in", ("payments", "invoice", "hybrid")),
                                (
                                    "filing_frequency__in",
                                    ("monthly", "two_monthly", "six_monthly"),
                                ),
                                ("period_anchor_month__isnull", False),
                                ("registered", True),
                            ),
                            models.Q(
                                ("basis", ""),
                                ("filing_frequency", ""),
                                ("gst_number", ""),
                                ("period_anchor_month__isnull", True),
                                ("registered", False),
                            ),
                            _connector="OR",
                        ),
                        name="gst_registration_state_fields",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_anchor_month__isnull", True),
                            models.Q(
                                ("period_anchor_month__gte", 1),
                                ("period_anchor_month__lte", 12),
                            ),
                            _connector="OR",
                        ),
                        name="gst_registration_anchor_range",
                    ),
                ],
            },
        ),
    ]
