# Generated by Django 6.1 on 2026-08-22 05:15

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_classify_sales_lines_for_gst"),
        ("tax", "0001_record_gst_arrangements"),
        ("workspaces", "0006_workspace_garden_experience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxTreatmentCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_treatment", models.CharField(max_length=16)),
                ("treatment", models.CharField(max_length=16)),
                ("reason", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_treatment_corrections",
                        to="sales.salesorderline",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "sales_order_line"],
                        name="gst_treatment_line_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("treatment", models.F("previous_treatment")), _negated=True
                        ),
                        name="gst_treatment_correction_changes_something",
                    )
                ],
            },
        ),
    ]
