# Generated by Django 6.1 on 2026-08-22 06:50

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0002_audit_tax_treatment_corrections"),
        ("workspaces", "0006_workspace_garden_experience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GstPeriodClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("basis", models.CharField(max_length=16)),
                ("filing_frequency", models.CharField(max_length=16)),
                ("filed_totals", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="The arrangement this period was filed under.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closures",
                        to="tax.gstregistration",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["period_start", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="gst_closure_period_ordered",
                    ),
                    models.UniqueConstraint(
                        fields=("workspace", "period_start", "period_end"),
                        name="gst_closure_period_unique",
                    ),
                ],
            },
        ),
    ]
