# Generated by Django 6.1 on 2026-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0003_record_filed_gst_periods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gstregistration",
            name="gst_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The IRD/GST number the registration is held under. Entered in any conventional form — 49-091-850, 136-410-132, or bare digits — and stored as nine digits.",
                max_length=16,
            ),
        ),
    ]
