# Generated by Django 5.2.8 on 2025-11-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("website", models.CharField(blank=True, max_length=1024, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunSQL("""
            INSERT INTO supplies_supplier (
                id,
                name,
                website,
                notes
            )
            SELECT
                id,
                name,
                website,
                notes
            FROM
                seeds_supplier;
        """)
    ]
