# Generated by Django 6.0.7 on 2026-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0002_supplier_workspace"),
        ("workspaces", "0006_workspace_garden_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="is_system_default",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Stands in for a supplier a Basic Garden workflow left unnamed. See supplies.defaults.ensure_default_supplier.",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system_default", True)),
                fields=("workspace",),
                name="supplier_one_system_default_per_workspace",
            ),
        ),
    ]
