# Generated by Django 6.1 on 2026-09-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0005_retire_suppliers"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record this duplicate was merged into. It keeps its own identity so anything written against it still resolves.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="supplies.supplier",
            ),
        ),
    ]
