# Generated by Django 6.0.7 on 2026-08-08 07:10

import django.core.validators
import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0002_inputapplicationtarget_seed_tray_generation_and_more"),
        ("inventory", "0006_stockreceipt_price_includes_tax"),
        ("plantings", "0025_seedtrayplanting_generation_and_more"),
        ("seedtrays", "0006_backfill_legacy_generations"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAllocationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("application_posted", "Input application posted"),
                            ("application_reversed", "Input application reversed"),
                            ("sowing_posted", "Sowing posted"),
                            ("sowing_corrected", "Sowing corrected"),
                            ("germination", "Germination observed"),
                            ("generation_closed", "Tray generation cleaned"),
                            ("output_finalized", "Batch output finalized"),
                            ("manual_recalculate", "Recalculated by an operator"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("posted_count", models.PositiveIntegerField(default=0)),
                ("reversed_count", models.PositiveIntegerField(default=0)),
                ("froze_output", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocation_runs",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("application_line", "Input application line"),
                            ("sowing_posting", "Sowing stock posting"),
                            ("generation_residual", "Tray generation residual"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("seed_tray_cell", "Tray cell"),
                            ("specific_plant", "Plant"),
                            ("batch_pool", "Unresolved batch pool"),
                            ("production_loss", "Production loss"),
                            ("unattributed", "Not attributable to a plant"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("seeds_sown", "Seeds or clusters sown"),
                            ("cell_volume", "Cell volume"),
                            ("per_plant", "Per plant"),
                            ("area", "Target area"),
                            ("equal_share", "Equal share of a cell"),
                            ("direct", "Whole source"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "basis_weight",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="This layer's share of the source, as a ratio.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=12,
                        max_digits=30,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "application_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="applications.inputapplicationline",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "generation_residual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="seedtrays.seedtraygenerationresidual",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="costing.costallocation",
                    ),
                ),
                (
                    "seed_tray_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="seedtrays.seedtraycell",
                    ),
                ),
                (
                    "seed_tray_generation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tray fill this cell was serving when the input went in.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="seedtrays.seedtraygeneration",
                    ),
                ),
                (
                    "sowing_posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="plantings.sowingstockposting",
                    ),
                ),
                (
                    "specific_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_allocations",
                        to="plantings.specificplant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="costing.costallocationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="costallocationrun",
            index=models.Index(fields=["batch", "created"], name="cost_run_batch_idx"),
        ),
        migrations.AddIndex(
            model_name="costallocation",
            index=models.Index(
                fields=["batch", "target_type"], name="cost_allocation_batch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costallocation",
            index=models.Index(
                fields=["specific_plant"], name="cost_allocation_plant_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("application_line__isnull", False),
                        ("generation_residual__isnull", True),
                        ("source_type", "application_line"),
                        ("sowing_posting__isnull", True),
                    ),
                    models.Q(
                        ("application_line__isnull", True),
                        ("generation_residual__isnull", True),
                        ("source_type", "sowing_posting"),
                        ("sowing_posting__isnull", False),
                    ),
                    models.Q(
                        ("application_line__isnull", True),
                        ("generation_residual__isnull", False),
                        ("source_type", "generation_residual"),
                        ("sowing_posting__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cost_allocation_source_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("seed_tray_cell__isnull", False),
                        ("specific_plant__isnull", True),
                        ("target_type", "seed_tray_cell"),
                    ),
                    models.Q(
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", False),
                        ("target_type", "specific_plant"),
                    ),
                    models.Q(
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", True),
                        (
                            "target_type__in",
                            ("batch_pool", "production_loss", "unattributed"),
                        ),
                    ),
                    _connector="OR",
                ),
                name="cost_allocation_target_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("seed_tray_generation__isnull", True),
                    ("target_type", "seed_tray_cell"),
                    _connector="OR",
                ),
                name="cost_allocation_generation_needs_cell",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("basis_weight__gte", 0)),
                name="cost_allocation_nonnegative_weight",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gte", 0)),
                name="cost_allocation_nonnegative_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount__isnull", True), ("unit_cost__isnull", True)),
                    models.Q(("amount__isnull", False), ("unit_cost__isnull", False)),
                    _connector="OR",
                ),
                name="cost_allocation_cost_and_amount_together",
            ),
        ),
    ]
