# Generated by Django 6.0.7 on 2026-08-10 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_point_applications_at_the_locations_app"),
        ("costing", "0001_initial"),
        ("inventory", "0007_point_stock_at_the_locations_app"),
        ("plantings", "0028_cohort_inventory_foundation"),
        ("seedtrays", "0006_backfill_legacy_generations"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costallocation",
            name="cost_allocation_target_identity",
        ),
        migrations.AddField(
            model_name="costallocation",
            name="plant_cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_allocations",
                to="plantings.plantcohort",
            ),
        ),
        migrations.AlterField(
            model_name="costallocation",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("seed_tray_cell", "Tray cell"),
                    ("specific_plant", "Plant"),
                    ("plant_cohort", "Plant cohort"),
                    ("batch_pool", "Unresolved batch pool"),
                    ("production_loss", "Production loss"),
                    ("unattributed", "Not attributable to a plant"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="costallocation",
            index=models.Index(
                fields=["plant_cohort"], name="cost_allocation_cohort_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("plant_cohort__isnull", True),
                        ("seed_tray_cell__isnull", False),
                        ("specific_plant__isnull", True),
                        ("target_type", "seed_tray_cell"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", True),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", False),
                        ("target_type", "specific_plant"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", False),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", True),
                        ("target_type", "plant_cohort"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", True),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", True),
                        (
                            "target_type__in",
                            ("batch_pool", "production_loss", "unattributed"),
                        ),
                    ),
                    _connector="OR",
                ),
                name="cost_allocation_target_identity",
            ),
        ),
    ]
