# Generated by Django 6.0.7 on 2026-08-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_inputapplicationtarget_plant_cohort'),
        ('costing', '0002_add_cohort_cost_targets'),
        ('inventory', '0011_report_indexes'),
        ('plantings', '0042_gardenplanting_and_more'),
        ('seedtrays', '0006_backfill_legacy_generations'),
        ('workspaces', '0006_workspace_garden_experience'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costallocation',
            name='cost_allocation_source_identity',
        ),
        migrations.AddField(
            model_name='costallocation',
            name='garden_planting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='plantings.gardenplanting'),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='source_type',
            field=models.CharField(choices=[('application_line', 'Input application line'), ('sowing_posting', 'Sowing stock posting'), ('generation_residual', 'Tray generation residual'), ('garden_planting', 'Garden planting purchase')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application_line__isnull', False), ('garden_planting__isnull', True), ('generation_residual__isnull', True), ('source_type', 'application_line'), ('sowing_posting__isnull', True)), models.Q(('application_line__isnull', True), ('garden_planting__isnull', True), ('generation_residual__isnull', True), ('source_type', 'sowing_posting'), ('sowing_posting__isnull', False)), models.Q(('application_line__isnull', True), ('garden_planting__isnull', True), ('generation_residual__isnull', False), ('source_type', 'generation_residual'), ('sowing_posting__isnull', True)), models.Q(('application_line__isnull', True), ('garden_planting__isnull', False), ('generation_residual__isnull', True), ('source_type', 'garden_planting'), ('sowing_posting__isnull', True)), _connector='OR'), name='cost_allocation_source_identity'),
        ),
    ]
