# Generated by Django 6.1 on 2026-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "costing",
            "0003_remove_costallocation_cost_allocation_source_identity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocationrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("application_posted", "Input application posted"),
                    ("application_reversed", "Input application reversed"),
                    ("sowing_posted", "Sowing posted"),
                    ("sowing_corrected", "Sowing corrected"),
                    ("germination", "Germination observed"),
                    ("germination_closed", "Germination closed"),
                    ("generation_closed", "Tray generation cleaned"),
                    ("output_finalized", "Batch output finalized"),
                    ("manual_recalculate", "Recalculated by an operator"),
                ],
                max_length=24,
            ),
        ),
    ]
