# Generated by Django 6.1 on 2026-09-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_inputapplicationtarget_plant_cohort"),
        ("costing", "0004_alter_costallocationrun_trigger"),
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("plantings", "0047_specificplantlocation_container_unit_and_more"),
        ("seedtrays", "0006_backfill_legacy_generations"),
        ("workspaces", "0007_workspace_seller_identity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costallocation",
            name="cost_allocation_source_identity",
        ),
        migrations.AddField(
            model_name="costallocation",
            name="container_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_allocations",
                to="inventory.inventoryunit",
            ),
        ),
        migrations.AlterField(
            model_name="costallocation",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("application_line", "Input application line"),
                    ("sowing_posting", "Sowing stock posting"),
                    ("generation_residual", "Tray generation residual"),
                    ("garden_planting", "Garden planting purchase"),
                    ("container_unit", "Container sold with the plant"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="costallocationrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("application_posted", "Input application posted"),
                    ("application_reversed", "Input application reversed"),
                    ("sowing_posted", "Sowing posted"),
                    ("sowing_corrected", "Sowing corrected"),
                    ("germination", "Germination observed"),
                    ("germination_closed", "Germination closed"),
                    ("generation_closed", "Tray generation cleaned"),
                    ("output_finalized", "Batch output finalized"),
                    ("container_sold", "Container sold with its plants"),
                    ("manual_recalculate", "Recalculated by an operator"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("application_line__isnull", False),
                        ("container_unit__isnull", True),
                        ("garden_planting__isnull", True),
                        ("generation_residual__isnull", True),
                        ("source_type", "application_line"),
                        ("sowing_posting__isnull", True),
                    ),
                    models.Q(
                        ("application_line__isnull", True),
                        ("container_unit__isnull", True),
                        ("garden_planting__isnull", True),
                        ("generation_residual__isnull", True),
                        ("source_type", "sowing_posting"),
                        ("sowing_posting__isnull", False),
                    ),
                    models.Q(
                        ("application_line__isnull", True),
                        ("container_unit__isnull", True),
                        ("garden_planting__isnull", True),
                        ("generation_residual__isnull", False),
                        ("source_type", "generation_residual"),
                        ("sowing_posting__isnull", True),
                    ),
                    models.Q(
                        ("application_line__isnull", True),
                        ("container_unit__isnull", True),
                        ("garden_planting__isnull", False),
                        ("generation_residual__isnull", True),
                        ("source_type", "garden_planting"),
                        ("sowing_posting__isnull", True),
                    ),
                    models.Q(
                        ("application_line__isnull", True),
                        ("container_unit__isnull", False),
                        ("garden_planting__isnull", True),
                        ("generation_residual__isnull", True),
                        ("source_type", "container_unit"),
                        ("sowing_posting__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cost_allocation_source_identity",
            ),
        ),
    ]
