# Generated by Django 6.1 on 2026-09-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_inputapplicationtarget_plant_cohort"),
        ("costing", "0005_container_cost_source"),
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("plantings", "0048_sell_cohort_quantity"),
        ("seedtrays", "0006_backfill_legacy_generations"),
        ("workspaces", "0007_workspace_seller_identity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costallocation",
            name="cost_allocation_target_identity",
        ),
        migrations.AlterField(
            model_name="costallocation",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("seed_tray_cell", "Tray cell"),
                    ("specific_plant", "Plant"),
                    ("plant_cohort", "Plant cohort"),
                    ("cohort_sale", "Cohort sale"),
                    ("batch_pool", "Unresolved batch pool"),
                    ("production_loss", "Production loss"),
                    ("unattributed", "Not attributable to a plant"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("plant_cohort__isnull", True),
                        ("seed_tray_cell__isnull", False),
                        ("specific_plant__isnull", True),
                        ("target_type", "seed_tray_cell"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", True),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", False),
                        ("target_type", "specific_plant"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", False),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", True),
                        ("target_type", "plant_cohort"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", False),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", True),
                        ("target_type", "cohort_sale"),
                    ),
                    models.Q(
                        ("plant_cohort__isnull", True),
                        ("seed_tray_cell__isnull", True),
                        ("specific_plant__isnull", True),
                        (
                            "target_type__in",
                            ("batch_pool", "production_loss", "unattributed"),
                        ),
                    ),
                    _connector="OR",
                ),
                name="cost_allocation_target_identity",
            ),
        ),
    ]
