# Generated by Django 6.1 on 2026-09-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0006_sell_cohort_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocationrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("application_posted", "Input application posted"),
                    ("application_reversed", "Input application reversed"),
                    ("sowing_posted", "Sowing posted"),
                    ("sowing_corrected", "Sowing corrected"),
                    ("germination", "Germination observed"),
                    ("germination_closed", "Germination closed"),
                    ("generation_closed", "Tray generation cleaned"),
                    ("output_finalized", "Batch output finalized"),
                    ("container_sold", "Container sold with its plants"),
                    ("fill_departure", "Plant left its container fill"),
                    ("manual_recalculate", "Recalculated by an operator"),
                ],
                max_length=24,
            ),
        ),
    ]
