# Generated by Django 6.1 on 2026-09-12 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costing", "0007_alter_costallocationrun_trigger"),
        ("plantings", "0051_coded_setting_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="FillDepartureRecalculation",
            fields=[
                (
                    "placement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="pending_cost_recalculation",
                        serialize=False,
                        to="plantings.specificplantlocation",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
