# Generated by Django 6.1 on 2026-09-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_container_fill_media'),
        ('costing', '0009_alter_costallocationrun_trigger'),
        ('inventory', '0017_alter_stocktaketarget_target_type'),
        ('plantings', '0053_counted_pot_numbering'),
        ('sales', '0014_salesreturnline_container_fill_fulfillmentcontainer'),
        ('seedtrays', '0013_alter_seedtraygenerationevent_event_type'),
        ('workspaces', '0008_assumption_variance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costallocation',
            name='cost_allocation_source_identity',
        ),
        migrations.AddField(
            model_name='costallocation',
            name='container_dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='sales.fulfillmentcontainer'),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='source_type',
            field=models.CharField(choices=[('application_line', 'Input application line'), ('sowing_posting', 'Sowing stock posting'), ('generation_residual', 'Tray generation residual'), ('garden_planting', 'Garden planting purchase'), ('container_unit', 'Container sold with the plant'), ('container_dispatch', 'Pot accompanying a sold plant')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application_line__isnull', False), ('container_dispatch__isnull', True), ('container_unit__isnull', True), ('garden_planting__isnull', True), ('generation_residual__isnull', True), ('source_type', 'application_line'), ('sowing_posting__isnull', True)), models.Q(('application_line__isnull', True), ('container_dispatch__isnull', True), ('container_unit__isnull', True), ('garden_planting__isnull', True), ('generation_residual__isnull', True), ('source_type', 'sowing_posting'), ('sowing_posting__isnull', False)), models.Q(('application_line__isnull', True), ('container_dispatch__isnull', True), ('container_unit__isnull', True), ('garden_planting__isnull', True), ('generation_residual__isnull', False), ('source_type', 'generation_residual'), ('sowing_posting__isnull', True)), models.Q(('application_line__isnull', True), ('container_dispatch__isnull', True), ('container_unit__isnull', True), ('garden_planting__isnull', False), ('generation_residual__isnull', True), ('source_type', 'garden_planting'), ('sowing_posting__isnull', True)), models.Q(('application_line__isnull', True), ('container_dispatch__isnull', True), ('container_unit__isnull', False), ('garden_planting__isnull', True), ('generation_residual__isnull', True), ('source_type', 'container_unit'), ('sowing_posting__isnull', True)), models.Q(('application_line__isnull', True), ('container_dispatch__isnull', False), ('container_unit__isnull', True), ('garden_planting__isnull', True), ('generation_residual__isnull', True), ('source_type', 'container_dispatch'), ('sowing_posting__isnull', True)), _connector='OR'), name='cost_allocation_source_identity'),
        ),
    ]
