# Generated by Django 6.1 on 2026-08-26 09:20

import django.core.validators
import django.db.models.deletion
import purchasing.models
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garden", "0007_gardenbed_kind"),
        ("inventory", "0014_remove_receipt_tax_defaults"),
        (
            "plantings",
            "0043_remove_sowingstockposting_sowing_posting_exactly_one_planting_and_more",
        ),
        ("supplies", "0004_supplier_tax_identity"),
        ("workspaces", "0007_workspace_seller_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("ordered_on", models.DateField()),
                ("expected_on", models.DateField(blank=True, null=True)),
                (
                    "currency_code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Enter a three-letter uppercase ISO 4217 currency code.",
                            )
                        ],
                    ),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "freight_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="supplies.supplier",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "unit_price_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "freight_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "cancelled_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=24,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                ("reason", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellations",
                        to="purchasing.purchaseorderline",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_on", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "unit_code",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("seed", "Seed"),
                            ("seed_cluster", "Seed cluster"),
                            ("ml", "Millilitre"),
                            ("l", "Litre"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("m2", "Square metre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "estimated_total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("ordered", "Ordered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to="supplies.supplier",
                    ),
                ),
                (
                    "source_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to="plantings.nurseryplanissue",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["required_on", "pk"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="requisition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_line",
                to="purchasing.purchaserequisition",
            ),
        ),
        migrations.CreateModel(
            name="ReceiptMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=24,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_matches",
                        to="purchasing.purchaseorderline",
                    ),
                ),
                (
                    "receipt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_matches",
                        to="inventory.stockreceiptline",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_reference", models.CharField(max_length=255)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "currency_code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Enter a three-letter uppercase ISO 4217 currency code.",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "supplier_name_snapshot",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("supplier_address_snapshot", models.TextField(blank=True, default="")),
                (
                    "supplier_gst_number_snapshot",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_invoices",
                        to="supplies.supplier",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="BusinessExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payee", models.CharField(blank=True, default="", max_length=255)),
                ("incurred_on", models.DateField()),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Future allocation kind such as equipment, channel, market, or delivery.",
                        max_length=32,
                    ),
                ),
                (
                    "allocation_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_expenses",
                        to="plantings.nurseryproductionplan",
                    ),
                ),
                (
                    "garden_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_expenses",
                        to="garden.gardenarea",
                    ),
                ),
                (
                    "production_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_expenses",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_expenses",
                        to="supplies.supplier",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="purchasing.expensecategory",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_expenses",
                        to="purchasing.supplierinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-incurred_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")], max_length=8
                    ),
                ),
                ("external_reference", models.CharField(max_length=255)),
                ("corrected_on", models.DateField()),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "attachment_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                (
                    "operation_key",
                    models.UUIDField(default=purchasing.models.operation_key),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="purchasing.supplierinvoice",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["corrected_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("is_freight", models.BooleanField(default=False)),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                    ),
                ),
                (
                    "expense_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_invoice_lines",
                        to="purchasing.expensecategory",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.supplierinvoice",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="purchasing.purchaseorderline",
                    ),
                ),
                (
                    "receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_invoice_lines",
                        to="inventory.stockreceiptline",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_on", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "operation_key",
                    models.UUIDField(default=purchasing.models.operation_key),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="purchasing.supplierpayment",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_payments",
                        to="supplies.supplier",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["paid_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-9"))
                        ],
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="purchasing.supplierinvoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="purchasing.supplierpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="purchasing_expense_category_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("workspace", "order_number"),
                name="purchasing_order_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseordercancellation",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", 0)),
                name="purchasing_order_cancel_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequisition",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchasing_requisition_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequisition",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_total_incl_tax__gte", 0)),
                name="purchasing_requisition_estimate_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchasing_order_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", 0)),
                name="purchasing_order_line_base_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("cancelled_quantity__gte", 0)),
                name="purchasing_order_line_cancelled_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", 0)),
                name="purchasing_receipt_match_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.UniqueConstraint(
                fields=("workspace", "supplier", "external_reference"),
                name="purchasing_supplier_invoice_reference_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicecorrection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="purchasing_invoice_correction_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicecorrection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "external_reference"),
                name="purchasing_invoice_correction_reference_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpayment",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="purchasing_supplier_payment_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "invoice"), name="purchasing_payment_invoice_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="purchasing_payment_allocation_positive",
            ),
        ),
    ]
