# Generated by Django 6.1 on 2026-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessexpense",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
