# Generated by Django 6.1 on 2026-08-27 09:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def preserve_legacy_deductible_amounts(apps, _schema_editor):
    """Treat historical unclassified GST as unclaimed rather than inventing a claim."""
    BusinessExpense = apps.get_model('purchasing', 'BusinessExpense')
    SupplierInvoiceLine = apps.get_model('purchasing', 'SupplierInvoiceLine')
    for model in (BusinessExpense, SupplierInvoiceLine):
        for row in model.objects.all().only('pk', 'total_incl_tax').iterator():
            model.objects.filter(pk=row.pk).update(deductible_amount=row.total_incl_tax)


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_businessexpense_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessexpense',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='apportionment_basis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='claim_input_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='claimable_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='recoverable_tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='tax_treatment',
            field=models.CharField(choices=[('standard', 'Standard-rated'), ('zero_rated', 'Zero-rated'), ('exempt', 'Exempt'), ('out_of_scope', 'Outside GST'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='apportionment_basis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='claim_input_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='claimable_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='recoverable_tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='tax_treatment',
            field=models.CharField(choices=[('standard', 'Standard-rated'), ('zero_rated', 'Zero-rated'), ('exempt', 'Exempt'), ('out_of_scope', 'Outside GST'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(
            preserve_legacy_deductible_amounts,
            migrations.RunPython.noop,
        ),
    ]
