# Generated by Django 6.1 on 2026-09-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_businessexpense_account_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record this duplicate was merged into. It keeps its own identity so anything written against it still resolves.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="purchasing.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Retired records stay readable everywhere they are already recorded, but are no longer offered as choices.",
            ),
        ),
    ]
