# Generated by Django 6.1 on 2026-09-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_expense_category_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessexpense',
            name='batch_cost_treatment',
            field=models.CharField(choices=[('excluded', 'Exclude from plant costs'), ('non_labor', 'Non-labor production cost')], default='excluded', help_text='Explicitly include only non-labor costs; allocate the amount after recoverable tax across batch outputs.', max_length=16),
        ),
    ]
