# Generated by Django 5.0.6 on 2024-07-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("notes", models.TextField(blank=True, null=True)),
                ("spacing", models.IntegerField(blank=True, null=True)),
                ("inter_row_spacing", models.IntegerField(blank=True, null=True)),
                ("plants_per_square_foot", models.IntegerField(blank=True, null=True)),
                ("germination_days_min", models.IntegerField(blank=True, null=True)),
                ("germination_days_max", models.IntegerField(blank=True, null=True)),
                ("maturity_days_min", models.IntegerField(blank=True, null=True)),
                ("maturity_days_max", models.IntegerField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plants.plantfamily",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("notes", models.TextField(blank=True, null=True)),
                ("spacing", models.IntegerField(blank=True, null=True)),
                ("inter_row_spacing", models.IntegerField(blank=True, null=True)),
                ("plants_per_square_foot", models.IntegerField(blank=True, null=True)),
                ("germination_days_min", models.IntegerField(blank=True, null=True)),
                ("germination_days_max", models.IntegerField(blank=True, null=True)),
                ("maturity_days_min", models.IntegerField(blank=True, null=True)),
                ("maturity_days_max", models.IntegerField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="plants.plant"
                    ),
                ),
            ],
        ),
    ]
