# Generated by Django 6.1 on 2026-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0003_maturity_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Retired records stay readable everywhere they are already recorded, but are no longer offered as choices.",
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Retired records stay readable everywhere they are already recorded, but are no longer offered as choices.",
            ),
        ),
        migrations.AddField(
            model_name="plantvariety",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Retired records stay readable everywhere they are already recorded, but are no longer offered as choices.",
            ),
        ),
    ]
