# Generated by Django 6.1 on 2026-09-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_retire_catalog_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record this duplicate was merged into. It keeps its own identity so anything written against it still resolves.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record this duplicate was merged into. It keeps its own identity so anything written against it still resolves.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="plants.plantfamily",
            ),
        ),
        migrations.AddField(
            model_name="plantvariety",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The record this duplicate was merged into. It keeps its own identity so anything written against it still resolves.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="plants.plantvariety",
            ),
        ),
    ]
