# Generated by Django 6.1 on 2026-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0005_merge_duplicate_catalog_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="reference_source",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="The reference set this record was installed from. Blank on a record the gardener made.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="reference_values",
            field=models.JSONField(
                default=dict,
                editable=False,
                help_text="What that set says about this record, field by field. A field still equal to it is still the set's; one that differs is the gardener's own.",
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="reference_source",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="The reference set this record was installed from. Blank on a record the gardener made.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="plantfamily",
            name="reference_values",
            field=models.JSONField(
                default=dict,
                editable=False,
                help_text="What that set says about this record, field by field. A field still equal to it is still the set's; one that differs is the gardener's own.",
            ),
        ),
        migrations.AddField(
            model_name="plantvariety",
            name="reference_source",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="The reference set this record was installed from. Blank on a record the gardener made.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="plantvariety",
            name="reference_values",
            field=models.JSONField(
                default=dict,
                editable=False,
                help_text="What that set says about this record, field by field. A field still equal to it is still the set's; one that differs is the gardener's own.",
            ),
        ),
    ]
