# Generated by Django 6.0.7 on 2026-08-10

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0002_workspace_override_tolerance_floor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('target_snapshot', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['target_content_type_id', 'target_object_id']},
        ),
        migrations.CreateModel(
            name='LabelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('void', 'Void')], default='active', max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.TextField(blank=True, default='')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='labels.labelidentity')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replacement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='labels.labelcode')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['-issued_at', '-pk']},
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('format', models.CharField(choices=[('qr', 'QR code'), ('code128', 'Code 128')], max_length=12)),
                ('payload_mode', models.CharField(choices=[('code', 'Bare code'), ('url', 'Application deep link')], default='code', max_length=8)),
                ('layout', models.CharField(choices=[('single', 'Single label'), ('sheet', 'Sheet'), ('roll', 'Roll printer')], max_length=12)),
                ('fields', models.JSONField(default=list)),
                ('dimensions', models.JSONField(default=dict)),
                ('built_in', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['name', 'pk']},
        ),
        migrations.CreateModel(
            name='LabelPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_snapshot', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='labels.labeltemplate')),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={'ordering': ['-created', '-pk']},
        ),
        migrations.CreateModel(
            name='LabelPrintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('target_snapshot', models.JSONField(default=dict)),
                ('payload', models.TextField()),
                ('is_reprint', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='labels.labelcode')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='labels.labelidentity')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='labels.labelprintjob')),
            ],
            options={'ordering': ['position']},
        ),
        migrations.AddConstraint(model_name='labelidentity', constraint=models.UniqueConstraint(fields=('workspace', 'target_content_type', 'target_object_id'), name='label_identity_workspace_target_unique')),
        migrations.AddConstraint(model_name='labelcode', constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='label_code_workspace_unique')),
        migrations.AddConstraint(model_name='labelcode', constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('identity',), name='label_code_one_active_per_identity')),
        migrations.AddConstraint(model_name='labeltemplate', constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='label_template_workspace_name_unique')),
        migrations.AddConstraint(model_name='labelprintitem', constraint=models.UniqueConstraint(fields=('job', 'position'), name='label_print_item_job_position_unique')),
    ]
