# Generated by Django 6.0.7 on 2026-08-12 08:21

import django.db.models.deletion
import django.utils.timezone
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0034_alter_nurseryplaninputrequirement_requirement_and_more"),
        ("seedtrays", "0006_backfill_legacy_generations"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pest", "Pest"),
                            ("disease", "Disease"),
                            ("damage", "Damage"),
                            ("vigor", "Vigor or stress"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "display_order", "name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HealthObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("follow_up_due_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("correction_reason", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "corrects",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="HealthEvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="health.healthobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthAffectedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_observation_memberships",
                        to="plantings.plantcohort",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_observation_memberships",
                        to="plantings.specificplant",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affected_stock",
                        to="health.healthobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthObservationDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("suspected", "Suspected"),
                            ("confirmed", "Confirmed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observation_links",
                        to="health.healthdiagnosis",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="health.healthobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthObservationScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.productionbatch",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.plantcohort",
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="seedtrays.seedtraygeneration",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scopes",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.specificplant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthObservationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("display_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="healthobservation",
            name="observation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="health.healthobservationtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthdiagnosis",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"),
                name="health_diagnosis_workspace_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthevidencelink",
            constraint=models.UniqueConstraint(
                fields=("observation", "url"),
                name="health_evidence_observation_url_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthaffectedstock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cohort__isnull", True),
                        ("plant__isnull", False),
                        ("quantity", 1),
                    ),
                    models.Q(
                        ("cohort__isnull", False),
                        ("plant__isnull", True),
                        ("quantity__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="health_affected_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthaffectedstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("observation", "plant"),
                name="health_affected_unique_plant",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthaffectedstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cohort__isnull", False)),
                fields=("observation", "cohort"),
                name="health_affected_unique_cohort",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthobservationdiagnosis",
            constraint=models.UniqueConstraint(
                fields=("observation", "diagnosis"),
                name="health_observation_diagnosis_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthobservationscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("batch__isnull", True),
                        ("cohort__isnull", True),
                        ("generation__isnull", True),
                        ("location__isnull", True),
                        ("plant__isnull", False),
                    ),
                    models.Q(
                        ("batch__isnull", True),
                        ("cohort__isnull", False),
                        ("generation__isnull", True),
                        ("location__isnull", True),
                        ("plant__isnull", True),
                    ),
                    models.Q(
                        ("batch__isnull", True),
                        ("cohort__isnull", True),
                        ("generation__isnull", False),
                        ("location__isnull", True),
                        ("plant__isnull", True),
                    ),
                    models.Q(
                        ("batch__isnull", False),
                        ("cohort__isnull", True),
                        ("generation__isnull", True),
                        ("location__isnull", True),
                        ("plant__isnull", True),
                    ),
                    models.Q(
                        ("batch__isnull", True),
                        ("cohort__isnull", True),
                        ("generation__isnull", True),
                        ("location__isnull", False),
                        ("plant__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="health_scope_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="healthobservationtype",
            constraint=models.UniqueConstraint(
                fields=("workspace", "code"), name="health_type_workspace_code_unique"
            ),
        ),
    ]
