# Generated by Django 6.0.7 on 2026-08-12 08:30

import django.db.models.deletion
import django.utils.timezone
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_inputapplicationtarget_plant_cohort"),
        ("health", "0002_seed_health_catalogs"),
        ("inventory", "0008_inventoryitem_container_footprint_m2_and_more"),
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0034_alter_nurseryplaninputrequirement_requirement_and_more"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_due_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_treatment",
                        to="applications.inputapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatments",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["application__applied_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HealthFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved"),
                            ("improving", "Improving"),
                            ("resolved", "Resolved"),
                            ("worsened", "Worsened"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "effectiveness",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("ineffective", "Ineffective"),
                            ("partial", "Partially effective"),
                            ("effective", "Effective"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("correction_reason", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "corrects",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction",
                        to="health.healthfollowup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="health.healthtreatment",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="QuarantineAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("quarantine", "Quarantine"),
                            ("release", "Release"),
                            ("escalate", "Escalate"),
                            ("cull", "Cull or discard"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="QuarantineActionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="health.quarantineaction",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.plantcohort",
                    ),
                ),
                (
                    "cohort_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.cohortoperation",
                    ),
                ),
                (
                    "lifecycle_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.plantlifecycleevent",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.specificplant",
                    ),
                ),
                (
                    "plant_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="plantings.specificplantlocation",
                    ),
                ),
                (
                    "stock_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuarantineCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quarantine_cases",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="quarantineaction",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="health.quarantinecase",
            ),
        ),
        migrations.CreateModel(
            name="QuarantineMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="health.quarantinecase",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quarantine_memberships",
                        to="plantings.plantcohort",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quarantine_memberships",
                        to="plantings.specificplant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="quarantineaction",
            constraint=models.UniqueConstraint(
                fields=("workspace", "idempotency_key"),
                name="quarantine_action_workspace_idempotent",
            ),
        ),
        migrations.AddConstraint(
            model_name="quarantinemember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cohort__isnull", True),
                        ("plant__isnull", False),
                        ("quantity", 1),
                    ),
                    models.Q(
                        ("cohort__isnull", False),
                        ("plant__isnull", True),
                        ("quantity__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="quarantine_member_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="quarantinemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("case", "plant"),
                name="quarantine_member_unique_plant",
            ),
        ),
        migrations.AddConstraint(
            model_name="quarantinemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cohort__isnull", False)),
                fields=("case", "cohort"),
                name="quarantine_member_unique_cohort",
            ),
        ),
    ]
