# Generated by Django 6.0.7 on 2026-08-09 01:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_rename_location_table"),
        ("workspaces", "0002_workspace_override_tolerance_floor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["display_order", "name", "pk"]},
        ),
        migrations.AddField(
            model_name="location",
            name="capacity_basis",
            field=models.CharField(
                choices=[
                    ("none", "Not tracked"),
                    ("trays", "Trays"),
                    ("containers", "Containers"),
                    ("plants", "Plants"),
                    ("area", "Area"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="capacity_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="path",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("greenhouse", "Greenhouse"),
                    ("tunnel", "Tunnel"),
                    ("bench", "Bench"),
                    ("bay", "Bay"),
                    ("receiving", "Receiving"),
                    ("storage", "Storage"),
                    ("growing", "Nursery or growing area"),
                    ("dispatch", "Customer dispatch"),
                    ("hold", "Customer hold"),
                    ("staging", "Dispatch staging"),
                    ("quarantine", "Quarantine"),
                    ("adjustment", "Adjustment"),
                    ("seed_packet", "Seed packet"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("capacity_basis", "none"), ("capacity_value__isnull", True)
                    ),
                    models.Q(
                        models.Q(("capacity_basis", "none"), _negated=True),
                        ("capacity_value__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="location_capacity_value_matches_basis",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_value__isnull", True),
                    ("capacity_value__gte", 0),
                    _connector="OR",
                ),
                name="location_capacity_value_nonnegative",
            ),
        ),
    ]
