# Generated by Django 6.0.7 on 2026-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_backfill_location_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("greenhouse", "Greenhouse"),
                    ("tunnel", "Tunnel"),
                    ("bench", "Bench"),
                    ("container", "Pot or container"),
                    ("bay", "Bay"),
                    ("receiving", "Receiving"),
                    ("storage", "Storage"),
                    ("growing", "Nursery or growing area"),
                    ("dispatch", "Customer dispatch"),
                    ("hold", "Customer hold"),
                    ("staging", "Dispatch staging"),
                    ("quarantine", "Quarantine"),
                    ("adjustment", "Adjustment"),
                    ("seed_packet", "Seed packet"),
                ],
                max_length=16,
            ),
        ),
    ]
