# Generated by Django 6.1 on 2026-08-25 21:34

import attachments.models
import attachments.storage
import django.db.models.deletion
import uuid
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("health", "0004_backfill_released_quarantine"),
        (
            "plantings",
            "0043_remove_sowingstockposting_sowing_posting_exactly_one_planting_and_more",
        ),
        ("workspaces", "0007_workspace_seller_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "original",
                    models.FileField(
                        max_length=255,
                        storage=attachments.storage.PrivateAttachmentStorage(),
                        upload_to=attachments.models._stored_image_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        max_length=255,
                        storage=attachments.storage.PrivateAttachmentStorage(),
                        upload_to=attachments.models._stored_thumbnail_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=32)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "harvest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_attachments",
                        to="plantings.harvest",
                    ),
                ),
                (
                    "health_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_attachments",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "nursery_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_attachments",
                        to="plantings.nurseryobservation",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_attachments",
                        to="plantings.specificplant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "pk"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "plant"],
                        name="attachments_workspa_bb010b_idx",
                    ),
                    models.Index(
                        fields=["workspace", "nursery_observation"],
                        name="attachments_workspa_d2a5dd_idx",
                    ),
                    models.Index(
                        fields=["workspace", "health_observation"],
                        name="attachments_workspa_2c77d4_idx",
                    ),
                    models.Index(
                        fields=["workspace", "harvest"],
                        name="attachments_workspa_f8f863_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("harvest__isnull", True),
                                ("health_observation__isnull", True),
                                ("nursery_observation__isnull", True),
                                ("plant__isnull", False),
                            ),
                            models.Q(
                                ("harvest__isnull", True),
                                ("health_observation__isnull", True),
                                ("nursery_observation__isnull", False),
                                ("plant__isnull", True),
                            ),
                            models.Q(
                                ("harvest__isnull", True),
                                ("health_observation__isnull", False),
                                ("nursery_observation__isnull", True),
                                ("plant__isnull", True),
                            ),
                            models.Q(
                                ("harvest__isnull", False),
                                ("health_observation__isnull", True),
                                ("nursery_observation__isnull", True),
                                ("plant__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="attachment_exactly_one_target",
                    )
                ],
            },
        ),
    ]
