# Generated by Django 6.0.7 on 2026-08-14 09:24

import django.core.validators
import django.db.models.deletion
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_stocktaketarget_review_revision_and_more'),
        ('plantings', '0035_alter_plantlifecycleevent_event_type'),
        ('plants', '0003_maturity_basis'),
        ('workspaces', '0004_workspace_sales_prices_include_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderNumberSequence',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='workspaces.workspace')),
                ('next_number', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('quote', 'Quote'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partially_fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=24)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Enter a three-letter uppercase ISO 4217 currency code.', regex='^[A-Z]{3}$')])),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('gross_ex_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('discount_total_ex_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('subtotal_ex_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('total_incl_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer')),
                ('workspace', models.ForeignKey(default=workspaces.models.get_default_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('released', 'Released'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='pending', editable=False, max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_allocations', to='inventory.inventoryunit')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_allocations', to='plantings.specificplant')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sales.salesorderallocation')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('seedling', 'Seedling'), ('tray', 'Serialized tray')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('discount_type', models.CharField(choices=[('none', 'No discount'), ('fixed', 'Fixed amount'), ('percentage', 'Percentage')], default='none', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('gross_ex_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('discount_ex_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('subtotal_ex_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('total_incl_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('tray_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryitem')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plants.plantvariety')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='salesorderallocation',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.salesorderline'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('workspace', 'order_number'), name='sales_order_workspace_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_type', 'seedling'), ('tray_item__isnull', True), ('variety__isnull', False)), models.Q(('line_type', 'tray'), ('tray_item__isnull', False), ('variety__isnull', True)), _connector='OR'), name='sales_line_target_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='sales_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_unit__isnull', True), ('plant__isnull', False)), models.Q(('inventory_unit__isnull', False), ('plant__isnull', True)), _connector='OR'), name='sales_allocation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='salesorderallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('plant',), name='sales_one_active_plant_reservation'),
        ),
        migrations.AddConstraint(
            model_name='salesorderallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('inventory_unit',), name='sales_one_active_unit_reservation'),
        ),
    ]
