# Generated by Django 6.0.7 on 2026-08-14 11:38

import django.core.validators
import django.db.models.deletion
import workspaces.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_healthtreatment_healthfollowup_quarantineaction_and_more"),
        ("inventory", "0010_stocktaketarget_review_revision_and_more"),
        ("locations", "0004_backfill_location_paths"),
        ("plantings", "0036_commerce_lifecycle_events"),
        ("sales", "0001_initial"),
        ("workspaces", "0004_workspace_sales_prices_include_tax"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FulfillmentNumberSequence",
            fields=[
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workspaces.workspace",
                    ),
                ),
                ("next_number", models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reserved", "Reserved"),
                    ("released", "Released"),
                    ("expired", "Expired"),
                    ("fulfilled", "Fulfilled"),
                    ("returned", "Returned"),
                ],
                default="pending",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Fulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("fulfillment_number", models.CharField(max_length=32)),
                ("fulfilled_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillments",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="sales.fulfillment",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["fulfilled_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FulfillmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commercial_position", models.PositiveIntegerField()),
                ("gross_ex_tax", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "discount_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("tax_total", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "cogs_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("cogs_provisional", models.BooleanField(default=False)),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_lines",
                        to="sales.salesorderallocation",
                    ),
                ),
                (
                    "fulfillment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.fulfillment",
                    ),
                ),
                (
                    "lifecycle_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_line",
                        to="plantings.plantlifecycleevent",
                    ),
                ),
                (
                    "stock_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_line",
                        to="inventory.stockmovement",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="FulfillmentPackagingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=9, max_digits=18)),
                ("base_unit", models.CharField(max_length=16)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "cogs_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "fulfillment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packaging_lines",
                        to="sales.fulfillment",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_packaging",
                        to="inventory.stocklot",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "stock_movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_packaging_line",
                        to="inventory.stockmovement",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("paid_on", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="sales.payment",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["paid_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("refunded_at", models.DateTimeField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="sales.payment",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="sales.refund",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["refunded_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="RefundLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_ex_tax", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "discount_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("tax_total", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "fulfillment_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_lines",
                        to="sales.fulfillmentline",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.refund",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("returned_at", models.DateTimeField()),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="health.healthobservation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "quarantine_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="health.quarantinecase",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="sales.salesreturn",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=workspaces.models.get_default_workspace_id,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["returned_at", "pk"],
            },
        ),
        migrations.AddField(
            model_name="refund",
            name="sales_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="sales.salesreturn",
            ),
        ),
        migrations.CreateModel(
            name="SalesReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("quarantined", "Quarantined"),
                            ("discarded", "Discarded"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "discard_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_return_discard_line",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "fulfillment_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="sales.fulfillmentline",
                    ),
                ),
                (
                    "lifecycle_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_return_line",
                        to="plantings.plantlifecycleevent",
                    ),
                ),
                (
                    "return_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_return_line",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "sales_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salesreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="fulfillment",
            constraint=models.UniqueConstraint(
                fields=("workspace", "fulfillment_number"),
                name="sales_fulfillment_workspace_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillment",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="sales_fulfillment_workspace_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentline",
            constraint=models.UniqueConstraint(
                fields=("fulfillment", "allocation"),
                name="sales_fulfillment_line_allocation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("commercial_position__gte", 1)),
                name="sales_fulfillment_line_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentpackagingline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_fulfillment_packaging_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="sales_payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="sales_payment_workspace_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="refundline",
            constraint=models.UniqueConstraint(
                fields=("refund", "fulfillment_line"),
                name="sales_refund_line_fulfillment_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturn",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="sales_return_workspace_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="sales_refund_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation_key"),
                name="sales_refund_workspace_operation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturnline",
            constraint=models.UniqueConstraint(
                fields=("sales_return", "fulfillment_line"),
                name="sales_return_line_fulfillment_unique",
            ),
        ),
    ]
