# Generated by Django 6.1 on 2026-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_classify_sales_lines_for_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='refund',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
