# Generated by Django 6.1 on 2026-09-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0047_specificplantlocation_container_unit_and_more"),
        ("sales", "0006_generalize_unit_sales_lines"),
    ]

    operations = [
        migrations.CreateModel(
            name="FulfillmentRider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cogs_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "fulfillment_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riders",
                        to="sales.fulfillmentline",
                    ),
                ),
                (
                    "lifecycle_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillment_rider",
                        to="plantings.plantlifecycleevent",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_riders",
                        to="plantings.specificplant",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fulfillment_line", "plant"),
                        name="sales_fulfillment_rider_unique",
                    )
                ],
            },
        ),
    ]
