# Generated by Django 6.1 on 2026-09-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantings", "0047_specificplantlocation_container_unit_and_more"),
        ("sales", "0007_fulfillmentrider"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillmentrider",
            name="return_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returned_fulfillment_rider",
                to="plantings.plantlifecycleevent",
            ),
        ),
    ]
