# Generated by Django 6.1 on 2026-09-02 07:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("plantings", "0047_specificplantlocation_container_unit_and_more"),
        ("plants", "0003_maturity_basis"),
        ("sales", "0008_fulfillmentrider_return_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesorderallocation",
            name="sales_allocation_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="salesorderline",
            name="sales_line_target_matches_type",
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="source_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="stock_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_allocations",
                to="inventory.stocklot",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("seedling", "Seedling"),
                    ("unit", "Individually numbered unit"),
                    ("lot_quantity", "Counted stock from a lot"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", False),
                        ("quantity__isnull", True),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", False),
                        ("plant__isnull", True),
                        ("quantity__isnull", True),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", True),
                        ("quantity__isnull", False),
                        ("source_location__isnull", False),
                        ("stock_lot__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sales_allocation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__isnull", True), ("quantity__gte", 1), _connector="OR"
                ),
                name="sales_allocation_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("item__isnull", True),
                        ("line_type", "seedling"),
                        ("variety__isnull", False),
                    ),
                    models.Q(
                        ("item__isnull", False),
                        ("line_type__in", ("unit", "lot_quantity")),
                        ("variety__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="sales_line_target_matches_type",
            ),
        ),
    ]
