# Generated by Django 6.1 on 2026-09-04 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("plantings", "0048_sell_cohort_quantity"),
        ("plants", "0003_maturity_basis"),
        ("sales", "0009_sell_counted_lot_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesorderallocation",
            name="sales_allocation_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="salesorderline",
            name="sales_line_target_matches_type",
        ),
        migrations.AddField(
            model_name="fulfillmentline",
            name="cohort_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fulfillment_line",
                to="plantings.cohortevent",
            ),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="plant_cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_allocations",
                to="plantings.plantcohort",
            ),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="cohort_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_return_line",
                to="plantings.cohortevent",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("seedling", "Seedling"),
                    ("unit", "Individually numbered unit"),
                    ("lot_quantity", "Counted stock from a lot"),
                    ("cohort_quantity", "Counted stock from a cohort"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", False),
                        ("plant_cohort__isnull", True),
                        ("quantity__isnull", True),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", False),
                        ("plant__isnull", True),
                        ("plant_cohort__isnull", True),
                        ("quantity__isnull", True),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", True),
                        ("plant_cohort__isnull", True),
                        ("quantity__isnull", False),
                        ("source_location__isnull", False),
                        ("stock_lot__isnull", False),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", True),
                        ("plant_cohort__isnull", False),
                        ("quantity__isnull", False),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="sales_allocation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("item__isnull", True),
                        ("line_type__in", ("seedling", "cohort_quantity")),
                        ("variety__isnull", False),
                    ),
                    models.Q(
                        ("item__isnull", False),
                        ("line_type__in", ("unit", "lot_quantity")),
                        ("variety__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="sales_line_target_matches_type",
            ),
        ),
    ]
