# Generated by Django 6.1 on 2026-09-05 00:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_sell_cohort_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("released", "Released"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("fulfilled", "Fulfilled"),
                    ("shortfall", "Short-supplied"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reserved", "Reserved"),
                    ("released", "Released"),
                    ("expired", "Expired"),
                    ("fulfilled", "Fulfilled"),
                    ("returned", "Returned"),
                    ("shortfall", "Short-supplied"),
                ],
                default="pending",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderShortfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("reason", models.TextField()),
                ("recorded_at", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortfalls",
                        to="sales.salesorderallocation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortfalls",
                        to="sales.salesorderline",
                    ),
                ),
                (
                    "replacement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_commitment",
                        to="sales.salesorderallocation",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)),
                        name="sales_shortfall_quantity_positive",
                    )
                ],
            },
        ),
    ]
