# Generated by Django 6.1 on 2026-09-06 06:33

import django.core.validators
import django.db.models.functions.math
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def backfill_quantities(apps, schema_editor):
    """Copy historical quantities only; never save or recalculate money."""
    alias = schema_editor.connection.alias
    allocation = apps.get_model('sales', 'SalesOrderAllocation')
    allocation.objects.using(alias).filter(quantity__isnull=True).update(quantity=1)
    fulfillment = apps.get_model('sales', 'FulfillmentLine')
    for row in fulfillment.objects.using(alias).select_related('allocation').iterator():
        fulfillment.objects.using(alias).filter(pk=row.pk).update(quantity=row.allocation.quantity)
    returned = apps.get_model('sales', 'SalesReturnLine')
    for row in returned.objects.using(alias).select_related('fulfillment_line').iterator():
        returned.objects.using(alias).filter(pk=row.pk).update(quantity=row.fulfillment_line.quantity)


def restore_implicit_identity_quantities(apps, schema_editor):
    """Restore the previous nullable representation after reversing the type."""
    model = apps.get_model('sales', 'SalesOrderAllocation')
    model.objects.using(schema_editor.connection.alias).filter(
        models.Q(plant__isnull=False) | models.Q(inventory_unit__isnull=False),
    ).update(quantity=None)


def refuse_measured_rollback(apps, schema_editor):
    """Never round measured stock or discard unit history during a rollback."""
    for name in ('SalesOrderLine', 'SalesOrderAllocation', 'FulfillmentLine', 'SalesReturnLine'):
        model = apps.get_model('sales', name)
        if model.objects.using(schema_editor.connection.alias).exclude(unit='each').exists():
            raise IrreversibleError('Measured commerce exists; restoring integer commerce would lose history.')


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("plantings", "0049_direct_sown_crop_event"),
        ("plants", "0003_maturity_basis"),
        ("sales", "0011_forward_sell_growing_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesorderallocation",
            name="sales_allocation_quantity_positive",
        ),
        migrations.RemoveConstraint(
            model_name="salesorderallocation",
            name="sales_allocation_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="salesorderline",
            name="sales_line_quantity_positive",
        ),
        migrations.RemoveConstraint(
            model_name="salesordershortfall",
            name="sales_shortfall_quantity_positive",
        ),
        migrations.AddField(
            model_name="fulfillmentline",
            name="quantity",
            field=models.DecimalField(decimal_places=9, default=1, max_digits=20),
        ),
        migrations.AddField(
            model_name="fulfillmentline",
            name="unit",
            field=models.CharField(
                choices=[
                    ("each", "Each"),
                    ("seed", "Seed"),
                    ("seed_cluster", "Seed cluster"),
                    ("ml", "Millilitre"),
                    ("l", "Litre"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("m2", "Square metre"),
                ],
                default="each",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="unit",
            field=models.CharField(
                choices=[
                    ("each", "Each"),
                    ("seed", "Seed"),
                    ("seed_cluster", "Seed cluster"),
                    ("ml", "Millilitre"),
                    ("l", "Litre"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("m2", "Square metre"),
                ],
                default="each",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="unit",
            field=models.CharField(
                choices=[
                    ("each", "Each"),
                    ("seed", "Seed"),
                    ("seed_cluster", "Seed cluster"),
                    ("ml", "Millilitre"),
                    ("l", "Litre"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("m2", "Square metre"),
                ],
                default="each",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="quantity",
            field=models.DecimalField(decimal_places=9, default=1, max_digits=20),
        ),
        migrations.AddField(
            model_name="salesreturnline",
            name="unit",
            field=models.CharField(
                choices=[
                    ("each", "Each"),
                    ("seed", "Seed"),
                    ("seed_cluster", "Seed cluster"),
                    ("ml", "Millilitre"),
                    ("l", "Litre"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("m2", "Square metre"),
                ],
                default="each",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_quantities, restore_implicit_identity_quantities),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="quantity",
            field=models.DecimalField(
                decimal_places=9,
                default=1,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-9"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=9,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-9"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesordershortfall",
            name="quantity",
            field=models.DecimalField(
                decimal_places=9,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-9"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", False),
                        ("plant_cohort__isnull", True),
                        ("quantity__isnull", False),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", False),
                        ("plant__isnull", True),
                        ("plant_cohort__isnull", True),
                        ("quantity__isnull", False),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", True),
                        ("plant_cohort__isnull", True),
                        ("quantity__isnull", False),
                        ("source_location__isnull", False),
                        ("stock_lot__isnull", False),
                    ),
                    models.Q(
                        ("inventory_unit__isnull", True),
                        ("plant__isnull", True),
                        ("plant_cohort__isnull", False),
                        ("quantity__isnull", False),
                        ("source_location__isnull", True),
                        ("stock_lot__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="sales_allocation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_allocation_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit__in",
                        ["each", "seed", "seed_cluster", "ml", "l", "g", "kg", "m2"],
                    )
                ),
                name="sales_allocation_unit_controlled",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stock_lot__isnull", False), ("unit", "each"), _connector="OR"
                ),
                name="sales_allocation_identity_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unit", "each"), _negated=True),
                    ("quantity", django.db.models.functions.math.Floor("quantity")),
                    _connector="OR",
                ),
                name="sales_allocation_each_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("inventory_unit__isnull", True), ("plant__isnull", True)),
                    ("quantity", 1),
                    _connector="OR",
                ),
                name="sales_allocation_identity_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit__in",
                        ["each", "seed", "seed_cluster", "ml", "l", "g", "kg", "m2"],
                    )
                ),
                name="sales_line_unit_controlled",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_type", "lot_quantity"), ("unit", "each"), _connector="OR"
                ),
                name="sales_line_identity_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unit", "each"), _negated=True),
                    ("quantity", django.db.models.functions.math.Floor("quantity")),
                    _connector="OR",
                ),
                name="sales_line_each_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesordershortfall",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_shortfall_quantity_positive",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_measured_rollback),
    ]
