# Generated by Django 6.1 on 2026-09-06 06:43

import django.db.models.functions.math
from django.db import migrations, models


def backfill_return_costs(apps, schema_editor):
    """Historical returns were whole dispatches, so copy their recorded cost."""
    model = apps.get_model('sales', 'SalesReturnLine')
    alias = schema_editor.connection.alias
    for row in model.objects.using(alias).select_related('fulfillment_line').iterator():
        model.objects.using(alias).filter(pk=row.pk).update(cogs_amount=row.fulfillment_line.cogs_amount)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("locations", "0005_alter_location_location_type"),
        ("plantings", "0049_direct_sown_crop_event"),
        ("sales", "0012_measured_quantity_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreturnline",
            name="cogs_amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.RunPython(backfill_return_costs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fulfillmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_fulfilled_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit__in",
                        ["each", "seed", "seed_cluster", "ml", "l", "g", "kg", "m2"],
                    )
                ),
                name="sales_fulfilled_unit_controlled",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unit", "each"), _negated=True),
                    ("quantity", django.db.models.functions.math.Floor("quantity")),
                    _connector="OR",
                ),
                name="sales_fulfilled_each_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_returned_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit__in",
                        ["each", "seed", "seed_cluster", "ml", "l", "g", "kg", "m2"],
                    )
                ),
                name="sales_returned_unit_controlled",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unit", "each"), _negated=True),
                    ("quantity", django.db.models.functions.math.Floor("quantity")),
                    _connector="OR",
                ),
                name="sales_returned_each_whole",
            ),
        ),
    ]
