# Generated by Django 6.1 on 2026-09-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stocktaketarget_target_type'),
        ('plantings', '0053_counted_pot_numbering'),
        ('sales', '0013_measured_snapshot_constraints'),
        ('seedtrays', '0013_alter_seedtraygenerationevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnline',
            name='container_fill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='container_returns', to='seedtrays.seedtraygeneration'),
        ),
        migrations.CreateModel(
            name='FulfillmentContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='container_dispatch', to='sales.fulfillmentline')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_dispatches', to='plantings.specificplantlocation')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_container_dispatches', to='inventory.stockmovement')),
                ('base_quantity', models.DecimalField(decimal_places=9, default=1, max_digits=20)),
                ('cogs_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('currency_code', models.CharField(max_length=3)),
            ],
        ),
    ]
