# Generated by Django 6.1 on 2026-09-23 23:42

from django.core.exceptions import ValidationError
from django.db import migrations, models


def backfill_cost_currencies(apps, schema_editor):
    """Restate what each existing row recorded, without correcting it.

    Every row written before this carried one code for both halves, and where
    the stock was raised abroad that code was wrong. Two of the four dispatch
    paths could in principle be re-derived — a counted lot and a numbered unit
    still carry the `currency_code` the cost was computed from, so a line drawn
    on a EUR lot could be relabelled EUR here. The other two cannot: a plant's
    and a cohort's cost is a share of layers that have been reversed and
    reposted since, so what currency the stored figure was in at dispatch is no
    longer readable. Correcting half the rows would leave a column that is
    right for some history and wrong for the rest, with nothing on the row
    saying which — so the backfill restates all four the same way, and none of
    them is presented as re-derived.

    A row with a cost therefore keeps the order's code as its cost's code, and
    a row with no cost gets the blank the new column stores for one. No stored
    figure changes and no new claim is made about a currency nobody typed. A
    dispatch posted from now on reads its currency from the stock it drew on;
    finding and settling the historical rows that are wrong is task 139's
    question, which is already the place where a dispatched cost is revisited
    after the fact.
    """
    alias = schema_editor.connection.alias
    lines = apps.get_model('sales', 'FulfillmentLine').objects.using(alias)
    lines.filter(cogs_amount__isnull=False).update(
        cogs_currency_code=models.F('currency_code'),
    )
    riders = apps.get_model('sales', 'FulfillmentRider').objects.using(alias)
    riders.filter(cogs_amount__isnull=False).update(
        cogs_currency_code=models.Subquery(
            lines.filter(pk=models.OuterRef('fulfillment_line_id')).values('currency_code')[:1],
        ),
    )


def require_a_currency_to_restate(apps, schema_editor):
    """Refuse the backfill where a stored cost has no currency to restate.

    `currency_code` has been non-null on both rows since they were added, so
    this should find nothing. It runs before the check constraint rather than
    after, because a row the constraint rejects would abort the migration with
    a database error naming the constraint and not the row.
    """
    alias = schema_editor.connection.alias
    lines = apps.get_model('sales', 'FulfillmentLine').objects.using(alias)
    unnamed = list(
        lines.filter(cogs_amount__isnull=False, currency_code='')
        .values_list('pk', flat=True)[:20]
    )
    if unnamed:
        listed = ', '.join(str(pk) for pk in unnamed)
        raise ValidationError(
            f'Fulfillment lines record a cost of sale in no currency: {listed}. '
            f'Give each one the currency its cost was recorded in, or clear the '
            f'cost, before adding the column that states which.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_stocktaketarget_target_type"),
        ("plantings", "0054_cohort_loss_correction"),
        ("sales", "0014_salesreturnline_container_fill_fulfillmentcontainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillmentline",
            name="cogs_currency_code",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="fulfillmentrider",
            name="cogs_currency_code",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.RunPython(require_a_currency_to_restate, migrations.RunPython.noop),
        migrations.RunPython(backfill_cost_currencies, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fulfillmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cogs_amount__isnull", True), ("cogs_currency_code", "")),
                    models.Q(
                        ("cogs_amount__isnull", False),
                        models.Q(("cogs_currency_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="sales_fulfillment_line_cost_currency_stated",
            ),
        ),
        migrations.AddConstraint(
            model_name="fulfillmentrider",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cogs_amount__isnull", True), ("cogs_currency_code", "")),
                    models.Q(
                        ("cogs_amount__isnull", False),
                        models.Q(("cogs_currency_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="sales_fulfillment_rider_cost_currency_stated",
            ),
        ),
    ]
